import { makeLevel, makeProblem, type StudyLevel } from './types'

const p = makeProblem
const L = makeLevel

export const MATH_LEVELS: StudyLevel[] = [
  L(0, 'math', 'Foundations', 'Whole numbers', ['integer', 'number sense', 'operations'], 'What is 12 + 8?',
    ['A whole number is a counting number: 0, 1, 2, 3, and up.', 'Add means put the two amounts together.', 'Subtract means take one amount away.'],
    ['Line the digits up by place value before you add.'],
    [p('What is 9 + 7?', 'B', ['14', '16', '15', '17'], '9 + 7 = 16.'), p('What is 27 + 18?', 'A', ['45', '35', '44', '47'], '7 + 8 = 15, write 5 carry 1. 2 + 1 + 1 = 4, so 45.'), p('What is 36 + 19 + 8?', 'C', ['53', '55', '63', '61'], '36 + 19 = 55, then 55 + 8 = 63.')]),
  L(1, 'math', 'Foundations', 'Fractions and percents', ['fraction', 'percent', 'ratio'], 'What is 1/2 of 10?',
    ['A fraction is a part of a whole. The bottom number is how many equal parts.', 'Percent means out of 100. 50% is the same as 1/2.', 'To take a fraction of a number, divide by the bottom, then multiply by the top.'],
    ['50% of a number is half of it. 25% is a quarter.'],
    [p('What is 1/2 of 18?', 'C', ['6', '12', '9', '36'], 'Half of 18 is 9.'), p('What is 1/4 of 40?', 'A', ['10', '15', '20', '8'], '40 / 4 = 10.'), p('What is 3/4 of 24?', 'B', ['6', '18', '12', '16'], '24 / 4 = 6, then 6 x 3 = 18.')]),
  L(2, 'math', 'Foundations', 'Ratios', ['ratio', 'proportion', 'unit rate'], 'If 2 pencils cost $6, what do 5 cost?',
    ['A ratio compares two amounts, like 2 to 3.', 'A unit rate is the cost or amount for 1 item.', 'Keep the same ratio by multiplying both sides by the same number.'],
    ['Find the price of 1 first, then multiply.'],
    [p('If 3 apples cost $6, what is 1 apple?', 'A', ['$2', '$3', '$9', '$1'], '6 / 3 = 2.'), p('If 3 apples cost $6, what do 5 apples cost?', 'B', ['$8', '$10', '$15', '$12'], 'One apple is $2, then 5 x 2 = 10.'), p('If 4 pencils cost $10, what do 6 pencils cost?', 'C', ['$12', '$18', '$15', '$20'], 'One pencil is 10/4 = 2.50. Then 6 x 2.50 = 15.')]),
  L(3, 'math', 'Algebra', 'Linear equations', ['linear equation', 'one-step', 'solve for'], 'Solve 2x + 4 = 10.',
    ['An equation says two sides are equal.', 'You can add, subtract, multiply, or divide both sides the same way.', 'Undo the last step first: subtract 4, then divide by 2.'],
    ['Do the opposite operation to isolate x.'],
    [p('Solve x + 7 = 12.', 'B', ['4', '5', '19', '7'], '12 - 7 = 5.'), p('Solve 3x = 18.', 'A', ['6', '15', '21', '3'], '18 / 3 = 6.'), p('Solve 2x + 4 = 10.', 'C', ['2', '4', '3', '6'], 'Subtract 4 to get 2x = 6, then x = 3.')]),
  L(4, 'math', 'Algebra', 'Linear functions', ['linear function', 'slope', 'rate of change', 'y-intercept'], 'Look at y = 3x + 5.',
    ['A linear function makes a straight line.', 'Write it as y = mx + b.', 'm is the slope: how much y changes when x goes up by 1.', 'b is the y-intercept: where the line hits the y-axis, when x is 0.'],
    ['Plug x = 0 to see the y-intercept. In Desmos, type y=3x+5 and watch the line.'],
    [p('In y = 3x + 5, what is the slope?', 'A', ['3', '5', '8', '0'], 'm is the number in front of x, so 3.'), p('In y = 3x + 5, what is y when x = 0?', 'B', ['3', '5', '0', '8'], 'When x is 0, y is the intercept 5.'), p('In y = 3x + 5, what is y when x = 4?', 'C', ['12', '17', '9', '8'], '3(4) + 5 = 12 + 5 = 17.')]),
  L(5, 'math', 'Algebra', 'Systems of equations', ['system', 'two equations', 'intersection'], 'x + y = 10 and x - y = 2.',
    ['A system is two equations at once.', 'The answer is the (x, y) point that works in both.', 'Add the equations if one variable cancels.'],
    ['In Desmos, graph both lines. The crossing point is the answer.'],
    [p('If x + y = 10 and x - y = 2, what is x?', 'B', ['4', '6', '8', '2'], 'Add: 2x = 12, so x = 6.'), p('Same system: x = 6 and x + y = 10. What is y?', 'A', ['4', '6', '8', '2'], '6 + y = 10, so y = 4.'), p('If x + y = 12 and x - y = 4, what is the point (x, y)?', 'C', ['(4, 8)', '(8, 8)', '(8, 4)', '(6, 6)'], 'Add: 2x = 16, x = 8. Then 8 + y = 12, y = 4.')]),
  L(6, 'math', 'Algebra', 'Inequalities', ['inequality', 'greater than', 'less than'], 'Solve x + 3 > 7.',
    ['> means greater than. < means less than.', 'Solve like an equation, but keep the inequality sign.', 'If you multiply or divide by a negative, flip the sign.'],
    ['Open circle on a number line means the endpoint is not included.'],
    [p('Solve x + 3 > 7.', 'A', ['x > 4', 'x < 4', 'x > 10', 'x = 4'], 'Subtract 3: x > 4.'), p('Solve 2x < 10.', 'B', ['x < 2', 'x < 5', 'x > 5', 'x = 5'], 'Divide both sides by 2: x < 5.'), p('Solve 2x + 4 > 12.', 'C', ['x > 8', 'x < 4', 'x > 4', 'x = 8'], 'Subtract 4: 2x > 8. Divide by 2: x > 4.')]),
  L(7, 'math', 'Advanced Math', 'Exponents', ['exponent', 'power', 'exponential'], 'What is 2^3?',
    ['An exponent tells how many times to multiply the base by itself.', '2^3 means 2 x 2 x 2.', 'Anything to the 0 power is 1 (if the base is not 0).'],
    ['When you multiply the same base, add the exponents.'],
    [p('What is 2^3?', 'B', ['6', '8', '9', '5'], '2 x 2 x 2 = 8.'), p('What is 3^2?', 'A', ['9', '6', '8', '5'], '3 x 3 = 9.'), p('2^2 x 2^3 equals', 'C', ['2^1', '2^6', '2^5', '4^5'], 'Same base, add the exponents: 2+3=5, so 2^5.')]),
  L(8, 'math', 'Advanced Math', 'Quadratics', ['quadratic', 'parabola', 'factor'], 'x^2 - 5x + 6 = 0.',
    ['A quadratic has an x^2 term. Its graph is a parabola.', 'Factor to (x - 2)(x - 3) = 0.', 'Then each piece can be 0, so x = 2 or x = 3.'],
    ['In Desmos, graph y = x^2 - 5x + 6 and read the x-intercepts.'],
    [p('The solutions of (x-2)(x-3)=0 are', 'A', ['2 and 3', '5 and 6', '-2 and -3', '0 and 6'], 'Set each factor to 0.'), p('Solve x^2 - 5x + 6 = 0.', 'B', ['1 and 6', '2 and 3', '5 and 6', '-2 and -3'], 'Factor to (x-2)(x-3)=0, then x=2 or 3.'), p('Solve x^2 - 7x + 12 = 0.', 'C', ['3 and 5', '2 and 6', '3 and 4', '1 and 12'], 'Factor to (x-3)(x-4)=0.')]),
  L(9, 'math', 'Geometry', 'Geometry basics', ['angle', 'triangle', 'geometry'], 'A triangle has angles 40 and 60. What is the third?',
    ['Angles in a triangle add to 180.', 'A right angle is 90 degrees.', 'A straight line is 180 degrees.'],
    ['Find the missing angle by subtracting the ones you know from 180.'],
    [p('Angles 40 and 60. Third angle?', 'A', ['80', '90', '100', '20'], '180 - 40 - 60 = 80.'), p('A triangle has angles 90 and 35. Third angle?', 'B', ['45', '55', '65', '125'], '180 - 90 - 35 = 55.'), p('A triangle has angles 2x, 3x, and 40. What is x?', 'C', ['20', '35', '28', '40'], '2x + 3x + 40 = 180, so 5x = 140, x = 28.')]),
  L(10, 'math', 'Geometry', 'Right triangles', ['pythagorean', 'hypotenuse', 'right triangle', 'trig'], 'Legs 3 and 4. Hypotenuse?',
    ['In a right triangle, a^2 + b^2 = c^2.', 'c is the hypotenuse, the side across from the right angle.', 'sin = opposite / hypotenuse.'],
    ['3-4-5 and 5-12-13 are common triples. Memorize them.'],
    [p('Legs 3 and 4. Hypotenuse?', 'B', ['6', '5', '7', '12'], '9 + 16 = 25, and sqrt 25 is 5.'), p('Legs 5 and 12. Hypotenuse?', 'A', ['13', '17', '10', '7'], '25 + 144 = 169, and sqrt 169 is 13.'), p('Hypotenuse 13 and one leg 5. Other leg?', 'C', ['8', '10', '12', '18'], '13^2 - 5^2 = 169 - 25 = 144, sqrt 144 is 12.')]),
  L(11, 'math', 'Data Analysis', 'Probability and data', ['probability', 'mean', 'median', 'statistics', 'data'], 'Mean of 2, 4, 6?',
    ['Mean is the average: add, then divide by how many.', 'Median is the middle when listed in order.', 'Probability is wanted outcomes over total outcomes.'],
    ['Put the list in order before you find the median.'],
    [p('Mean of 2, 4, 6?', 'A', ['4', '6', '12', '3'], '(2+4+6)/3 = 4.'), p('Mean of 3, 5, 7, 9?', 'B', ['5', '6', '7', '24'], '(3+5+7+9)/4 = 24/4 = 6.'), p('Mean of 10, 10, 4, and 8?', 'C', ['9', '7', '8', '32'], '(10+10+4+8)/4 = 32/4 = 8.')]),
  L(12, 'math', 'Foundations', 'Order of operations', ['order of operations', 'pemdas', 'parentheses'], 'What is 3 + 2 x 4?',
    ['Do parentheses first, then exponents, then multiply and divide left to right, then add and subtract left to right.', 'Multiplication does not wait for addition just because addition is written first.', '3 + 2 x 4 is 3 + 8, not 5 x 4.'],
    ['Circle the multiply or divide before you add.'],
    [p('What is 3 + 2 x 4?', 'A', ['11', '20', '9', '14'], '2 x 4 = 8, then 3 + 8 = 11.'), p('What is 18 - 6 / 3?', 'B', ['4', '16', '12', '6'], '6 / 3 = 2, then 18 - 2 = 16.'), p('What is 2(5 + 3)^2 / 4?', 'C', ['8', '16', '32', '64'], 'Parentheses 8, square 64, times 2 is 128, divide by 4 is 32.')]),
  L(13, 'math', 'Foundations', 'Integers and negatives', ['integer', 'negative', 'absolute value'], 'What is -3 + 8?',
    ['A negative number is left of 0 on the number line.', 'Adding a negative moves left. Subtracting a negative is the same as adding.', 'Two negatives multiply to a positive.'],
    ['Think of money: -3 is a $3 debt. Adding 8 leaves you with $5.'],
    [p('What is -3 + 8?', 'B', ['-11', '5', '11', '-5'], 'Start at -3 and move 8 right to 5.'), p('What is 4 - (-6)?', 'A', ['10', '-2', '2', '-10'], 'Minus a negative is plus: 4 + 6 = 10.'), p('What is (-2)(-5) + (-3)?', 'C', ['13', '-13', '7', '-7'], '(-2)(-5)=10, then 10 + (-3)=7.')]),
  L(14, 'math', 'Foundations', 'Decimals', ['decimal', 'place value', 'tenths'], 'What is 1.4 + 0.35?',
    ['Line up the decimal points before you add or subtract.', '1.4 is 14 tenths. 0.35 is 35 hundredths.', 'Multiplying decimals: multiply as whole numbers, then count total digits after the points.'],
    ['Write 1.40 instead of 1.4 so the places match.'],
    [p('What is 1.4 + 0.35?', 'A', ['1.75', '1.39', '4.75', '0.49'], '1.40 + 0.35 = 1.75.'), p('What is 2.5 x 0.2?', 'B', ['5', '0.5', '0.05', '2.7'], '25 x 2 = 50, two decimal places, so 0.50.'), p('What is 3.6 - 1.45?', 'C', ['2.25', '5.05', '2.15', '2.05'], '3.60 - 1.45 = 2.15.')]),
  L(15, 'math', 'Foundations', 'Mixed numbers', ['mixed number', 'improper fraction'], 'What is 1 1/2 + 2 1/4?',
    ['A mixed number is a whole plus a fraction, like 1 1/2.', 'Convert to improper fractions, or add wholes and fractions separately.', '1 1/2 = 3/2. 2 1/4 = 9/4.'],
    ['Give the fractions a common denominator before you add.'],
    [p('What is 1 1/2 + 1/2?', 'A', ['2', '1', '3', '2 1/2'], '1 + 1/2 + 1/2 = 2.'), p('What is 2 1/4 + 1 1/4?', 'B', ['3', '3 1/2', '3 1/4', '4'], 'Wholes 3, fractions 2/4 = 1/2, so 3 1/2.'), p('What is 3 2/3 - 1 1/6?', 'C', ['2', '2 1/6', '2 1/2', '3'], '3 4/6 - 1 1/6 = 2 3/6 = 2 1/2.')]),
  L(16, 'math', 'Foundations', 'Percent of a number', ['percent', 'percent of'], 'What is 20% of 80?',
    ['Percent means hundredths. 20% is 0.20.', 'Of means multiply.', '20% of 80 is 0.20 x 80 = 16.'],
    ['10% is move the decimal one place left. 20% is double that.'],
    [p('What is 10% of 90?', 'A', ['9', '10', '19', '81'], '10% of 90 is 9.'), p('What is 25% of 80?', 'B', ['15', '20', '25', '40'], '25% is one fourth, and 80 / 4 = 20.'), p('What is 15% of 240?', 'C', ['24', '30', '36', '48'], '10% is 24, 5% is 12, so 15% is 36.')]),
  L(17, 'math', 'Foundations', 'Percent change', ['percent change', 'percent increase', 'percent decrease'], 'A price goes from 40 to 50. What is the percent increase?',
    ['Percent change is (new - old) / old, then times 100.', 'Increase uses a positive change. Decrease uses a negative change, then drop the sign and say decrease.', 'The old value is always the denominator.'],
    ['Do not divide by the new number. The start value is the whole.'],
    [p('From 40 to 50, percent increase?', 'A', ['25%', '20%', '10%', '50%'], '(50-40)/40 = 10/40 = 25%.'), p('From 80 to 60, percent decrease?', 'B', ['20%', '25%', '30%', '15%'], '(80-60)/80 = 20/80 = 25%.'), p('A $200 ticket becomes $260. Percent increase?', 'C', ['26%', '23%', '30%', '60%'], '60/200 = 0.30, so 30%.')]),
  L(18, 'math', 'Foundations', 'Proportions', ['proportion', 'cross multiply'], 'If 4/x = 8/10, what is x?',
    ['A proportion says two ratios are equal.', 'Cross multiply: 4 x 10 = 8x.', 'Then solve the one-step equation.'],
    ['Keep matching units on top and matching units on bottom.'],
    [p('If 2/5 = 6/x, what is x?', 'A', ['15', '10', '12', '3'], '2x = 30, so x = 15.'), p('If 4/x = 8/10, what is x?', 'B', ['8', '5', '2', '20'], '40 = 8x, so x = 5.'), p('If 3/7 = 12/x, what is x?', 'C', ['16', '21', '28', '36'], '3x = 84, so x = 28.')]),
  L(19, 'math', 'Foundations', 'Unit rates', ['unit rate', 'per', 'rate'], 'A car travels 180 miles in 3 hours. What is the speed?',
    ['A unit rate is the amount for 1 of something.', 'Divide the first amount by the second amount.', '180 miles / 3 hours = 60 miles per hour.'],
    ['The word “per” means divide.'],
    [p('180 miles in 3 hours. Miles per hour?', 'A', ['60', '540', '177', '30'], '180 / 3 = 60.'), p('12 muffins cost $18. Cost of 1 muffin?', 'B', ['$1.20', '$1.50', '$2.00', '$6.00'], '18 / 12 = 1.50.'), p('A printer makes 240 pages in 8 minutes. Pages per minute?', 'C', ['20', '24', '30', '32'], '240 / 8 = 30.')]),
  L(20, 'math', 'Foundations', 'Unit conversion', ['unit conversion', 'dimensional analysis', 'convert'], 'How many minutes are in 2.5 hours?',
    ['Multiply by a fraction that equals 1, such as 60 min / 1 hour.', 'The unit you cancel goes on the bottom.', '2.5 hours x 60 minutes/hour = 150 minutes.'],
    ['Write the units. If they do not cancel to the asked unit, flip the fraction.'],
    [p('How many minutes are in 2 hours?', 'A', ['120', '60', '24', '200'], '2 x 60 = 120.'), p('How many inches are in 4 feet?', 'B', ['36', '48', '12', '4'], '4 x 12 = 48.'), p('A trip is 3.5 hours. How many minutes?', 'C', ['180', '200', '210', '350'], '3.5 x 60 = 210.')]),
  L(21, 'math', 'Algebra', 'Multi-step equations', ['multi-step', 'two-step equation'], 'Solve 5x - 7 = 18.',
    ['Undo addition or subtraction first, then undo multiplication.', 'Keep both sides balanced.', 'Check by plugging the answer back in.'],
    ['If you see parentheses, distribute first.'],
    [p('Solve 5x - 7 = 18.', 'A', ['5', '11', '2', '25'], '5x = 25, so x = 5.'), p('Solve 4x + 9 = 29.', 'B', ['4', '5', '8', '10'], '4x = 20, so x = 5.'), p('Solve 3(x - 2) = 21.', 'C', ['5', '7', '9', '11'], 'x - 2 = 7, so x = 9.')]),
  L(22, 'math', 'Algebra', 'Equations with fractions', ['fraction equation', 'clear denominators'], 'Solve x/4 + 1/2 = 2.',
    ['Multiply every term by the common denominator to clear fractions.', 'Then solve the leftover integer equation.', 'For x/4 + 1/2 = 2, multiply by 4 to get x + 2 = 8.'],
    ['The LCD of 4 and 2 is 4. One multiply clears both fractions.'],
    [p('Solve x/4 = 3.', 'A', ['12', '7', '3/4', '1'], 'x = 12.'), p('Solve x/3 + 2 = 6.', 'B', ['8', '12', '4', '18'], 'x/3 = 4, so x = 12.'), p('Solve x/4 + 1/2 = 2.', 'C', ['4', '5', '6', '8'], 'Multiply by 4: x + 2 = 8, so x = 6.')]),
  L(23, 'math', 'Algebra', 'Absolute value equations', ['absolute value', '|x|'], 'Solve |x| = 5.',
    ['Absolute value is distance from 0, so it is never negative.', '|x| = 5 means x = 5 or x = -5.', 'If |x| = a negative number, there is no solution.'],
    ['Split into two ordinary equations after you isolate the absolute value.'],
    [p('Solve |x| = 5.', 'A', ['5 or -5', '5 only', '-5 only', 'no solution'], 'Distance 5 is both 5 and -5.'), p('Solve |x - 2| = 3.', 'B', ['5 only', '5 or -1', '2 or 3', '1 or -1'], 'x - 2 = 3 or x - 2 = -3, so x = 5 or -1.'), p('Solve |2x| = 8.', 'C', ['4 only', '8 or -8', '4 or -4', '2 or -2'], '2x = 8 or 2x = -8, so x = 4 or -4.')]),
  L(24, 'math', 'Algebra', 'Slope from two points', ['slope', 'rise over run', 'two points'], 'What is the slope from (1, 2) to (4, 8)?',
    ['Slope m = (y2 - y1) / (x2 - x1).', 'Rise is the change in y. Run is the change in x.', 'A horizontal line has slope 0. A vertical line has undefined slope.'],
    ['In Desmos, plot both points and type y - 2 = m(x - 1) after you find m.'],
    [p('Slope from (1, 2) to (4, 8)?', 'A', ['2', '3', '6', '1/2'], '(8-2)/(4-1) = 6/3 = 2.'), p('Slope from (0, 5) to (10, 5)?', 'B', ['1', '0', 'undefined', '5'], 'y does not change, so slope is 0.'), p('Slope from (-2, 1) to (2, 9)?', 'C', ['1', '4', '2', '8'], '(9-1)/(2-(-2)) = 8/4 = 2.')]),
  L(25, 'math', 'Algebra', 'Point-slope and standard form', ['point-slope', 'standard form'], 'Write the line through (2, 3) with slope 4.',
    ['Point-slope: y - y1 = m(x - x1).', 'Slope-intercept: y = mx + b.', 'Standard form: Ax + By = C, usually integers.'],
    ['Start in point-slope, then rearrange if the choices look different.'],
    [p('Point-slope through (2, 3) with slope 4?', 'A', ['y - 3 = 4(x - 2)', 'y - 2 = 4(x - 3)', 'y + 3 = 4(x + 2)', 'y = 4x'], 'Plug into y - y1 = m(x - x1).'), p('y - 3 = 4(x - 2) in slope-intercept is', 'B', ['y = 4x - 3', 'y = 4x - 5', 'y = 4x + 5', 'y = 2x + 3'], 'y = 4x - 8 + 3 = 4x - 5.'), p('3x + 2y = 12, slope is', 'C', ['3/2', '2/3', '-3/2', '6'], '2y = -3x + 12, so m = -3/2.')]),
  L(26, 'math', 'Algebra', 'Parallel and perpendicular lines', ['parallel', 'perpendicular', 'negative reciprocal'], 'A line has slope 2. What slope is perpendicular?',
    ['Parallel lines have equal slopes.', 'Perpendicular lines have slopes that multiply to -1.', 'The perpendicular slope is the negative reciprocal: flip and change the sign.'],
    ['Slope 2 becomes -1/2. Slope -3/4 becomes 4/3.'],
    [p('Perpendicular to slope 2?', 'A', ['-1/2', '2', '1/2', '-2'], 'Flip 2 to 1/2 and change the sign.'), p('Parallel to y = -3x + 1?', 'B', ['3', '-3', '1/3', '-1/3'], 'Same slope, -3.'), p('A line through (0, 0) perpendicular to y = (1/4)x is', 'C', ['y = (1/4)x', 'y = 4x', 'y = -4x', 'y = -x/4'], 'Negative reciprocal of 1/4 is -4.')]),
  L(27, 'math', 'Algebra', 'Interpreting slope and intercept', ['interpret slope', 'rate of change', 'y-intercept meaning'], 'C = 20 + 3t. What does 3 mean?',
    ['In a real story, slope is the rate: how much the output changes per 1 input.', 'The intercept is the starting value when the input is 0.', 'Units matter: 3 dollars per hour is not 3 hours.'],
    ['Read the labels on x and y before you pick a sentence.'],
    [p('C = 20 + 3t. What is 3?', 'A', ['Cost rises $3 each hour', 'The start cost is $3', 'Time is 3 hours', 'Total cost is $3'], 'Slope is the rate, $3 per hour.'), p('C = 20 + 3t. What is 20?', 'B', ['Hours worked', 'Starting cost in dollars', 'Cost per hour', 'Total hours'], 'When t = 0, C = 20.'), p('Score = 400 + 8w. After 5 weeks the model predicts', 'C', ['40', '400', '440', '408'], '400 + 8(5) = 440.')]),
  L(28, 'math', 'Algebra', 'Systems by substitution', ['substitution', 'system'], 'y = 2x and x + y = 9.',
    ['Substitution means replace one variable with an expression.', 'If y = 2x, then x + 2x = 9.', 'Solve for the leftover variable, then plug back.'],
    ['Use substitution when one equation is already solved for x or y.'],
    [p('y = 2x and x + y = 9. What is x?', 'A', ['3', '6', '9', '2'], 'x + 2x = 9, so x = 3.'), p('Then y is', 'B', ['3', '6', '9', '5'], 'y = 2(3) = 6.'), p('y = x + 4 and 2x + y = 19. The point is', 'C', ['(5, 8)', '(7, 11)', '(5, 9)', '(6, 7)'], '2x + (x + 4) = 19, 3x = 15, x = 5, y = 9.')]),
  L(29, 'math', 'Algebra', 'Systems by elimination', ['elimination', 'linear combination'], '2x + y = 10 and x - y = 2.',
    ['Elimination means add or subtract so one variable cancels.', 'You may multiply an equation first so the coefficients match.', 'Then substitute to get the other value.'],
    ['If the signs are the same, subtract. If they are opposite, add.'],
    [p('2x + y = 10 and x - y = 2. What is x after adding?', 'A', ['4', '6', '8', '2'], '3x = 12 is wrong wait: 2x+x=3x, y-y=0, 10+2=12, x=4.'), p('Same system, y is', 'B', ['4', '2', '6', '8'], '4 - y = 2, so y = 2.'), p('3x + 2y = 16 and 3x - 2y = 8. What is x?', 'C', ['2', '3', '4', '8'], 'Add: 6x = 24, x = 4.')]),
  L(30, 'math', 'Algebra', 'Graphing linear inequalities', ['linear inequality', 'shade', 'half-plane'], 'Graph y > 2x - 1.',
    ['Graph the boundary line first as if it were y = 2x - 1.', 'Use a dashed line for > or <. Use a solid line for ≥ or ≤.', 'Shade the side that makes the inequality true. Test (0, 0) if it is not on the line.'],
    ['In Desmos, type y>2x-1 and the shade appears automatically.'],
    [p('For y > 2x - 1 the boundary is', 'A', ['dashed', 'solid', 'a point', 'a circle'], '> does not include the line, so dashed.'), p('Does (0, 0) satisfy y > 2x - 1?', 'B', ['no', 'yes', 'only on the line', 'cannot tell'], '0 > -1 is true, so shade toward the origin.'), p('Which point is in y ≤ -x + 4?', 'C', ['(0, 5)', '(5, 0)', '(1, 2)', '(6, -1)'], '1 + 2 = 3 ≤ 4, so (1, 2) works. (0,5) is 5>4.')]),
  L(31, 'math', 'Algebra', 'Compound inequalities', ['compound inequality', 'and', 'or'], 'Solve -1 < x + 2 ≤ 5.',
    ['And means the overlap, a single interval.', 'Or means two rays, often for |x| > a.', 'Do the same operation to all three parts of a three-part inequality.'],
    ['If you multiply by a negative, flip both inequality signs.'],
    [p('Solve -1 < x + 2 ≤ 5. The left piece gives', 'A', ['x > -3', 'x < -3', 'x > 3', 'x = -1'], 'Subtract 2: -3 < x.'), p('The full solution is', 'B', ['-1 < x ≤ 5', '-3 < x ≤ 3', 'x ≤ 3', 'x > -3'], 'Subtract 2 from all parts: -3 < x ≤ 3.'), p('Solve 2x ≥ 8 or x + 1 < 0.', 'C', ['x ≥ 4 only', 'x < -1 only', 'x ≥ 4 or x < -1', '4 ≤ x < -1'], 'Two separate rays joined by or.')]),
  L(32, 'math', 'Algebra', 'Systems of inequalities', ['system of inequalities', 'overlap', 'feasible region'], 'y ≥ x and y < -x + 4.',
    ['Graph each inequality.', 'The solution is the overlap of the shaded regions.', 'A test point inside the overlap must work in every inequality.'],
    ['In Desmos, type both inequalities. The darker overlap is the answer region.'],
    [p('The solution of a system of inequalities is', 'A', ['the overlap', 'either shade', 'the intercepts only', 'one line'], 'Both must be true, so only the overlap.'), p('Does (1, 2) satisfy y ≥ x and y < -x + 4?', 'B', ['no', 'yes', 'only the first', 'only the second'], '2 ≥ 1 and 2 < 3, both true.'), p('Does (3, 1) satisfy the same system?', 'C', ['yes', 'only y ≥ x', 'no', 'cannot graph'], '1 ≥ 3 is false, so the point is out.')]),
  L(33, 'math', 'Advanced Math', 'Negative and zero exponents', ['negative exponent', 'zero exponent'], 'What is 5^0 and 2^{-3}?',
    ['a^0 = 1 if a is not 0.', 'a^{-n} = 1 / a^n.', '2^{-3} = 1/8.'],
    ['A negative exponent is not a negative number. It is a reciprocal.'],
    [p('What is 5^0?', 'A', ['1', '0', '5', '-5'], 'Any nonzero base to the 0 is 1.'), p('What is 2^{-3}?', 'B', ['-6', '1/8', '-8', '8'], '1 / 2^3 = 1/8.'), p('What is 3^{-2} x 3^4?', 'C', ['3^{-8}', '1/9', '9', '3^6'], 'Add exponents: 3^{2} = 9.')]),
  L(34, 'math', 'Advanced Math', 'Radicals', ['radical', 'square root', 'simplify radical'], 'Simplify √50.',
    ['√(ab) = √a · √b.', 'Pull out perfect squares: √50 = √(25·2) = 5√2.', '√a · √a = a for a ≥ 0.'],
    ['Look for 4, 9, 16, 25, 36, 49 inside the radical.'],
    [p('Simplify √50.', 'A', ['5√2', '25√2', '10√5', '√25'], '√(25·2) = 5√2.'), p('Simplify √72.', 'B', ['6√3', '6√2', '8√2', '36√2'], '√(36·2) = 6√2.'), p('√12 + √27 equals', 'C', ['√39', '√3', '5√3', '13'], '2√3 + 3√3 = 5√3.')]),
  L(35, 'math', 'Advanced Math', 'Rational exponents', ['rational exponent', 'fractional exponent'], 'What is 8^{2/3}?',
    ['a^{m/n} is the nth root of a, then raised to m.', 'The denominator is the root. The numerator is the power.', '8^{2/3} = (cube root of 8)^2 = 2^2 = 4.'],
    ['Do the root first when the number is a nice power.'],
    [p('What is 8^{1/3}?', 'A', ['2', '4', '8', '24'], 'Cube root of 8 is 2.'), p('What is 8^{2/3}?', 'B', ['2', '4', '16', '64/3'], '(cube root of 8)^2 = 4.'), p('What is 16^{3/4}?', 'C', ['2', '4', '8', '12'], '(fourth root of 16)^3 = 2^3 = 8.')]),
  L(36, 'math', 'Advanced Math', 'Polynomials', ['polynomial', 'combine like terms', 'distribute'], 'Simplify (2x + 3) + (x - 8).',
    ['Add or subtract like terms only: x^2 with x^2, x with x, numbers with numbers.', 'Distribute a minus sign to every term in the second parentheses.', 'Degree is the highest power.'],
    ['Write highest power first so you do not drop a term.'],
    [p('(2x + 3) + (x - 8) equals', 'A', ['3x - 5', '3x + 11', 'x - 5', '2x - 5'], '2x + x and 3 - 8.'), p('(5x^2 + x) - (2x^2 - 4x) equals', 'B', ['3x^2 - 3x', '3x^2 + 5x', '7x^2 - 3x', '3x^2 + x'], '5x^2-2x^2 and x-(-4x)=5x.'), p('(x + 3)(x + 4) equals', 'C', ['x^2 + 7', 'x^2 + 12', 'x^2 + 7x + 12', '2x + 7'], 'FOIL: x^2 + 4x + 3x + 12.')]),
  L(37, 'math', 'Advanced Math', 'Factoring quadratics', ['factor', 'trinomial'], 'Factor x^2 + 7x + 12.',
    ['Find two numbers that multiply to the constant and add to the middle coefficient.', 'For x^2 + 7x + 12, 3 and 4 work.', 'Then (x + 3)(x + 4).'],
    ['If the leading coefficient is not 1, factor out a GCF first when you can.'],
    [p('Factor x^2 + 7x + 12.', 'A', ['(x+3)(x+4)', '(x+2)(x+6)', '(x+1)(x+12)', '(x-3)(x-4)'], '3+4=7 and 3x4=12.'), p('Factor x^2 - 8x + 15.', 'B', ['(x-1)(x-15)', '(x-3)(x-5)', '(x+3)(x+5)', '(x-8)(x+1)'], '-3 and -5 multiply to 15 and add to -8.'), p('Factor 2x^2 + 6x.', 'C', ['2x(x + 6)', 'x(2x + 6)', '2x(x + 3)', '(2x+3)(x)'], 'GCF 2x leaves x + 3.')]),
  L(38, 'math', 'Advanced Math', 'Difference of squares', ['difference of squares', 'a^2 - b^2'], 'Factor x^2 - 16.',
    ['a^2 - b^2 = (a - b)(a + b).', 'x^2 - 16 is x^2 - 4^2, so (x - 4)(x + 4).', 'This does not work for a^2 + b^2 over the reals.'],
    ['If both terms are perfect squares and you see a minus, use this pattern immediately.'],
    [p('Factor x^2 - 16.', 'A', ['(x-4)(x+4)', '(x-8)(x+2)', '(x-16)(x+1)', '(x-4)^2'], 'Squares  x and 4, minus in the middle.'), p('Factor 9x^2 - 25.', 'B', ['(9x-5)(x+5)', '(3x-5)(3x+5)', '(3x-25)(3x+1)', '(9x-25)(x+1)'], 'a is 3x and b is 5.'), p('Solve x^2 - 49 = 0.', 'C', ['7 only', '-7 only', '7 or -7', '49'], '(x-7)(x+7)=0.')]),
  L(39, 'math', 'Advanced Math', 'Quadratic formula', ['quadratic formula', 'discriminant'], 'Solve x^2 + 3x - 10 = 0.',
    ['x = (-b ± √(b^2 - 4ac)) / (2a).', 'The discriminant D = b^2 - 4ac tells you 2, 1, or 0 real roots.', 'Use this when factoring is messy.'],
    ['In Desmos, graph y = ax^2+bx+c and read the x-intercepts.'],
    [p('For x^2 + 3x - 10 = 0, a, b, c are', 'A', ['1, 3, -10', '1, -3, 10', '3, 1, -10', '1, 3, 10'], 'Standard form ax^2+bx+c.'), p('Discriminant of x^2 + 3x - 10 is', 'B', ['9', '49', '29', '-31'], '9 + 40 = 49.'), p('The solutions are', 'C', ['1 and -10', '5 and 2', '2 and -5', '10 and -1'], '(-3 ± 7)/2 gives 2 and -5.')]),
  L(40, 'math', 'Advanced Math', 'Completing the square', ['completing the square'], 'Rewrite x^2 + 6x + 5 as a square plus a number.',
    ['Take half the x-coefficient, then square it.', 'For x^2 + 6x, half of 6 is 3, and 3^2 is 9.', 'x^2 + 6x + 5 = (x + 3)^2 - 9 + 5 = (x + 3)^2 - 4.'],
    ['This is how vertex form is born.'],
    [p('Half of the 6 in x^2 + 6x is', 'A', ['3', '6', '9', '12'], 'Half the linear coefficient.'), p('That half, squared, is', 'B', ['3', '9', '36', '6'], '3^2 = 9.'), p('x^2 + 6x + 5 equals', 'C', ['(x+3)^2 + 5', '(x+3)^2 + 4', '(x+3)^2 - 4', '(x+6)^2 - 4'], 'Add 9 and subtract 9: (x+3)^2 - 4.')]),
  L(41, 'math', 'Advanced Math', 'Vertex form', ['vertex form', 'vertex', 'axis of symmetry'], 'y = (x - 2)^2 + 5. Where is the vertex?',
    ['y = a(x - h)^2 + k has vertex (h, k).', 'If a > 0 the parabola opens up. If a < 0 it opens down.', 'The axis of symmetry is x = h.'],
    ['Watch the sign: (x - 2) means h is +2, not -2.'],
    [p('Vertex of y = (x - 2)^2 + 5?', 'A', ['(2, 5)', '(-2, 5)', '(2, -5)', '(5, 2)'], 'h=2, k=5.'), p('Vertex of y = -2(x + 1)^2 + 4?', 'B', ['(1, 4)', '(-1, 4)', '(1, -4)', '(-1, -4)'], '(x+1) is (x-(-1)).'), p('Axis of symmetry of y = (x - 6)^2 - 1 is', 'C', ['y = -1', 'x = -6', 'x = 6', 'y = 6'], 'Vertical line through the vertex x-value.')]),
  L(42, 'math', 'Advanced Math', 'Quadratic word problems', ['projectile', 'maximum height', 'quadratic word'], 'h = -16t^2 + 32t + 6. When is the height 6?',
    ['Set the expression equal to the asked value.', 'The vertex time is t = -b/(2a) for a maximum or minimum.', 'Ignore a negative time if the story starts at t = 0.'],
    ['In Desmos, graph the quadratic and a horizontal line at the asked height.'],
    [p('h = -16t^2 + 32t + 6. Height at t=0?', 'A', ['6', '32', '16', '0'], 'Plug t=0: h=6.'), p('Time of max height is t = -b/(2a) =', 'B', ['2', '1', '16', '32'], '-32 / (2(-16)) = 1.'), p('Max height is', 'C', ['6', '16', '22', '32'], 'h(1) = -16+32+6 = 22.')]),
  L(43, 'math', 'Advanced Math', 'Exponential growth and decay', ['exponential growth', 'exponential decay', 'compound'], 'A = 200(1.05)^t. What is 1.05?',
    ['A = P(1 + r)^t is growth. A = P(1 - r)^t is decay.', 'The base is the multiplier each time period.', '1.05 means 5% growth per period.'],
    ['If the story says “halves every 3 years,” the base is 1/2 and t is in groups of 3.'],
    [p('In A = 200(1.05)^t, 1.05 means', 'A', ['5% growth each period', '5% of 200', '105 years', 'decay'], '1 + 0.05 = 1.05.'), p('A = 80(0.5)^t. After 2 periods A is', 'B', ['40', '20', '160', '80.5'], '80 x 1/4 = 20.'), p('Start 500, grow 8% for 3 years. Model is', 'C', ['500(0.08)^3', '500 + 8^3', '500(1.08)^3', '500(1.8)^3'], 'Multiply by 1.08 each year.')]),
  L(44, 'math', 'Advanced Math', 'Arithmetic sequences', ['arithmetic sequence', 'common difference'], '2, 5, 8, 11, ... What is the 10th term?',
    ['An arithmetic sequence adds the same d each time.', 'a_n = a_1 + (n - 1)d.', 'Here a_1 = 2 and d = 3.'],
    ['Count the number of jumps, not the term number, when you add d.'],
    [p('Common difference of 2, 5, 8, 11 is', 'A', ['3', '2', '4', '6'], '5-2=3.'), p('10th term is', 'B', ['29', '29', '32', '30'], '2 + 9x3 = 29.'), p('Sum of first 4 terms is', 'C', ['11', '20', '26', '32'], '2+5+8+11=26.')]),
  L(45, 'math', 'Advanced Math', 'Geometric sequences', ['geometric sequence', 'common ratio'], '3, 6, 12, 24, ... What is the 6th term?',
    ['A geometric sequence multiplies by the same r each time.', 'a_n = a_1 · r^{n-1}.', 'Here a_1 = 3 and r = 2.'],
    ['If r is a fraction, the terms shrink. If r is negative, the signs flip.'],
    [p('Common ratio of 3, 6, 12, 24 is', 'A', ['2', '3', '4', '6'], '6/3=2.'), p('6th term is', 'B', ['48', '96', '192', '36'], '3 x 2^5 = 96.'), p('If 80, 40, 20, ..., the 5th term is', 'C', ['10', '20', '5', '2.5'], '80, 40, 20, 10, then 5.')]),
  L(46, 'math', 'Advanced Math', 'Function notation', ['function notation', 'f(x)'], 'If f(x) = 3x - 1, what is f(4)?',
    ['f(a) means plug x = a into the rule.', 'f(x) = 5 is an equation asking which x gives output 5.', 'The graph point is (input, output).'],
    ['Do the inside first for f(g(2)).'],
    [p('f(x)=3x-1. f(4)=', 'A', ['11', '12', '3', '4'], '3(4)-1=11.'), p('f(x)=3x-1. If f(x)=8, x=', 'B', ['3', '3', '8', '7'], '3x-1=8, 3x=9, x=3.'), p('If f(2)=7 and f(x)=2x+b, then b=', 'C', ['3', '5', '3', '11'], '4+b=7, b=3.')]),
  L(47, 'math', 'Advanced Math', 'Domain and range', ['domain', 'range'], 'What x-values are allowed in f(x) = 1/(x-3)?',
    ['Domain is allowed inputs. Range is allowed outputs.', 'You cannot divide by 0. You cannot take an even root of a negative in the reals.', 'A graph’s left-right spread is domain. Up-down spread is range.'],
    ['Set the denominator not equal to 0 and solve.'],
    [p('Domain of 1/(x-3) excludes', 'A', ['3', '0', '1', '-3'], 'x-3=0 when x=3.'), p('Domain of √(x-2) is', 'B', ['x > 2', 'x ≥ 2', 'x ≤ 2', 'all x'], 'Inside the square root must be ≥ 0.'), p('Range of y = x^2 + 1 is', 'C', ['all real y', 'y ≥ 1', 'y ≥ 0', 'y > 1'], 'The parabola’s lowest point is 1.')]),
  L(48, 'math', 'Advanced Math', 'Function composition', ['composition', 'f(g(x))'], 'f(x)=x+2 and g(x)=3x. What is f(g(4))?',
    ['f(g(x)) means do g first, then feed that output into f.', 'g(f(x)) is a different order and usually a different number.', 'f(g(4)) = f(12) if g(4)=12.'],
    ['Write a placeholder: f(something) = something + 2.'],
    [p('g(4) if g(x)=3x is', 'A', ['12', '7', '4', '3'], '3x4=12.'), p('f(g(4)) if f(x)=x+2 is', 'B', ['6', '14', '12', '8'], 'f(12)=14.'), p('g(f(4)) is', 'C', ['14', '12', '18', '10'], 'f(4)=6, then g(6)=18.')]),
  L(49, 'math', 'Advanced Math', 'Inverse functions', ['inverse function', 'f inverse'], 'If f(2)=5, what is f^{-1}(5)?',
    ['An inverse swaps inputs and outputs.', 'If f(2)=5, then f^{-1}(5)=2.', 'Graphs of inverses reflect over y = x.'],
    ['To find a formula, swap x and y, then solve for y.'],
    [p('If f(2)=5, then f^{-1}(5)=', 'A', ['2', '5', '1/5', '7'], 'Swap the pair.'), p('f(x)=2x+1. f^{-1}(7)=', 'B', ['15', '3', '4', '6'], '2x+1=7, x=3.'), p('The inverse of y=x/4 is', 'C', ['y=4/x', 'y=x-4', 'y=4x', 'y=x+4'], 'Swap and multiply by 4.')]),
  L(50, 'math', 'Advanced Math', 'Rational expressions', ['rational expression', 'simplify fraction'], 'Simplify (x^2 - 9)/(x-3) for x ≠ 3.',
    ['Factor the top and bottom, then cancel common factors.', 'You must keep the excluded values from the original denominator.', '(x-3)(x+3)/(x-3) = x+3, x≠3.'],
    ['Cancel factors, not terms. You cannot cancel the 3 in (x+3)/3 unless the whole (x+3) is a factor.'],
    [p('(x^2-9)/(x-3) simplifies to', 'A', ['x+3, x≠3', 'x-3', 'x', '9'], 'Difference of squares, then cancel.'), p('(2x)/(4x) for x≠0 is', 'B', ['2x', '1/2', '2', '4'], '2/4 = 1/2.'), p('(x^2+5x)/(x) for x≠0 is', 'C', ['x+5', 'x+5x', 'x+5', '5'], 'x(x+5)/x = x+5.')]),
  L(51, 'math', 'Advanced Math', 'Rational equations', ['rational equation', 'extraneous'], 'Solve 1/x + 1/2 = 1.',
    ['Multiply through by the LCD to clear denominators.', 'Solve the leftover equation.', 'Check every answer in the original. A value that makes a denominator 0 is extraneous.'],
    ['Write the LCD of every denominator you see, including the variable one.'],
    [p('LCD of 1/x + 1/2 is', 'A', ['2x', 'x', '2', 'x+2'], 'Needs both 2 and x.'), p('Solve 1/x + 1/2 = 1.', 'B', ['1', '2', '1/2', '4'], '2 + x = 2x, so x=2.'), p('Solve 2/(x-1)=4. Check x=1?', 'C', ['x=1.5 and 1 is fine', 'x=1.5; 1 is illegal', 'no solution', 'x=3'], '2=4(x-1), x=1.5. x=1 zeros the bottom.')]),
  L(52, 'math', 'Advanced Math', 'Nonlinear systems', ['nonlinear system', 'line and parabola'], 'y = x^2 and y = 2x + 3.',
    ['Set the expressions equal if both are solved for y.', 'A line can hit a parabola 0, 1, or 2 times.', 'In Desmos, graph both and read every crossing.'],
    ['After you find x, plug back to get y. Report the asked coordinate.'],
    [p('Set x^2 = 2x + 3. Rearranged:', 'A', ['x^2 - 2x - 3 = 0', 'x^2 + 2x + 3 = 0', 'x^2 = 3', 'x=2'], 'Bring all terms left.'), p('Solutions for x are', 'B', ['3 and 1', '3 and -1', '2 and -3', '0 and 3'], '(x-3)(x+1)=0.'), p('The intersection points are', 'C', ['(3,9) and (-1,1)', '(3,6) and (-1,-1)', '(3,9) and (-1,1)', '(3,9) and (1,5)'], 'y=x^2 so (3,9) and (-1,1).')]),
  L(53, 'math', 'Advanced Math', 'Remainder theorem', ['remainder theorem', 'factor theorem'], 'What is the remainder when p(x)=x^2-3x+4 is divided by x-1?',
    ['The remainder when p(x) is divided by (x - a) is p(a).', 'If p(a)=0, then (x-a) is a factor.', 'This is faster than long division for SAT/ACT remainders.'],
    ['x+2 is (x-(-2)), so plug -2.'],
    [p('Remainder of x^2-3x+4 divided by x-1?', 'A', ['2', '0', '4', '1'], 'p(1)=1-3+4=2.'), p('Is x-2 a factor of x^2-5x+6?', 'B', ['no', 'yes', 'only sometimes', 'cannot tell'], 'p(2)=4-10+6=0, so yes.'), p('p(x)=x^3-x. p(-1)=', 'C', ['-2', '2', '0', '1'], '(-1)^3 - (-1) = -1 + 1 = 0.')]),
  L(54, 'math', 'Advanced Math', 'Complex numbers', ['complex number', 'imaginary', 'i^2'], 'What is i^2?',
    ['i^2 = -1 by definition.', '(a+bi)+(c+di)=(a+c)+(b+d)i.', '(a+bi)(c+di)=ac-bd + (ad+bc)i.'],
    ['Treat i like a variable, then replace i^2 with -1 at the end.'],
    [p('i^2 equals', 'A', ['-1', '1', 'i', '0'], 'Definition of i.'), p('(2+3i)+(1-5i) equals', 'B', ['3-2i', '3-2i', '1-2i', '3+8i'], '2+1 and 3-5.'), p('(1+i)(2-i) equals', 'C', ['2-i', '3+i', '3+i', '1-2i'], '2 -i +2i -i^2 = 2 +i +1 = 3+i.')]),
  L(55, 'math', 'Advanced Math', 'Absolute value functions', ['absolute value function', 'v-shape'], 'Graph y = |x - 2| + 1.',
    ['y = |x| is a V with vertex at the origin.', 'y = |x - h| + k moves the vertex to (h, k).', 'The graph never goes below k if the coefficient of the absolute value is positive.'],
    ['In Desmos, type y=abs(x-2)+1 and read the corner.'],
    [p('Vertex of y = |x - 2| + 1 is', 'A', ['(2, 1)', '(-2, 1)', '(2, -1)', '(1, 2)'], 'Inside zero at x=2, then +1.'), p('y = |x| at x=-4 is', 'B', ['-4', '4', '0', '8'], 'Distance from 0 is 4.'), p('Solve |x-1| = 3.', 'C', ['4 only', '1 and 3', '4 and -2', '3 and -3'], 'x-1=3 or x-1=-3.')]),
  L(56, 'math', 'Advanced Math', 'Piecewise functions', ['piecewise', 'piecewise function'], 'f(x)= x+1 if x<0, and 2x if x≥0. What is f(-2)?',
    ['A piecewise function uses different rules on different intervals.', 'Check which piece the input belongs to before you plug in.', 'At a boundary, use the piece that includes that endpoint.'],
    ['Circle the inequality that matches the number you were given.'],
    [p('f(-2) if f is x+1 for x<0 is', 'A', ['-1', ' -4', '2', '0'], '-2+1=-1.'), p('f(3) if the other piece is 2x for x≥0 is', 'B', ['4', '6', '3', '1'], '2x3=6.'), p('f(0) using 2x when x≥0 is', 'C', ['1', '2', '0', 'undefined'], '0 is in the second piece.')]),
  L(57, 'math', 'Advanced Math', 'Equivalent expressions', ['equivalent expressions', 'rewrite'], 'Which expression equals 2(x + 4) - x?',
    ['Equivalent expressions have the same value for every allowed x.', 'Distribute, combine like terms, or factor to match a choice.', 'Plug in a friendly number if the algebra is messy, then confirm.'],
    ['SAT Advanced Math loves rewriting one form into another.'],
    [p('2(x+4)-x equals', 'A', ['x+8', '2x+8', 'x+4', '3x+8'], '2x+8-x=x+8.'), p('(x+3)^2 equals', 'B', ['x^2+9', 'x^2+6x+9', 'x^2+3x+9', '2x+9'], 'Square the binomial fully.'), p('Which matches (3x^2y)/(xy) for x,y≠0?', 'C', ['3xy', '3x', '3x', '3y'], '3x^{2}y / xy = 3x.')]),
  L(58, 'math', 'Data Analysis', 'Mean, median, and mode', ['mean', 'median', 'mode'], 'For 2, 2, 4, 9, what is the median?',
    ['Mean is the average. Median is the middle of the ordered list. Mode is the most frequent value.', 'For an even count, median is the average of the two middle numbers.', 'An outlier pulls the mean more than the median.'],
    ['Always sort before you name the median.'],
    [p('Median of 2, 2, 4, 9?', 'A', ['3', '2', '4', '4.25'], 'Middle pair 2 and 4, average 3.'), p('Mode of 2, 2, 4, 9?', 'B', ['4', '2', '9', 'none'], '2 appears twice.'), p('Mean of 2, 2, 4, 9?', 'C', ['3', '4', '4.25', '2'], '17/4=4.25.')]),
  L(59, 'math', 'Data Analysis', 'Range and IQR', ['range', 'iqr', 'quartile', 'outlier'], 'Data: 1, 3, 5, 7, 9. What is the range?',
    ['Range is max minus min.', 'IQR is Q3 minus Q1, the middle 50%.', 'A common outlier fence is 1.5 IQR below Q1 or above Q3.'],
    ['Range reacts to one extreme value. IQR is more resistant.'],
    [p('Range of 1, 3, 5, 7, 9?', 'A', ['8', '5', '4', '9'], '9-1=8.'), p('Median of that list is', 'B', ['3', '5', '7', '4'], 'The middle 5.'), p('IQR if Q1=3 and Q3=7 is', 'C', ['10', '5', '4', '3.5'], '7-3=4.')]),
  L(60, 'math', 'Data Analysis', 'Scatterplots and trend lines', ['scatterplot', 'line of best fit', 'regression'], 'A line of best fit is y = 2x + 1. What does it predict at x=4?',
    ['A trend line summarizes the cloud, not every point.', 'Prediction uses the line: plug in x.', 'A residual is actual y minus predicted y.'],
    ['In Desmos, paste the table and type y1 ~ ax1 + b to get the fit.'],
    [p('Predict y at x=4 if y=2x+1.', 'A', ['9', '8', '7', '4'], '8+1=9.'), p('If a point is (4, 11), residual is', 'B', ['9', '2', '-2', '11'], '11-9=2.'), p('A positive slope means', 'C', ['y falls as x rises', 'no association', 'y tends to rise as x rises', 'causation'], 'Association, not automatically cause.')]),
  L(61, 'math', 'Data Analysis', 'Correlation vs causation', ['correlation', 'causation', 'association'], 'Ice cream sales and sunburns both rise in July. Does ice cream cause sunburns?',
    ['Association means they move together. Causation means one produces the other.', 'A lurking variable can drive both.', 'SAT wording: “associated with,” not “makes.”'],
    ['If the study is observational, do not pick a cause-and-effect claim.'],
    [p('Ice cream and sunburns rise together. Best conclusion?', 'A', ['They are associated', 'Ice cream causes burns', 'Burns cause ice cream', 'No relationship'], 'Same season, not a cause.'), p('A randomized experiment can support', 'B', ['only association', 'a causal claim', 'no conclusion', 'bias only'], 'Random assignment is the usual path to cause.'), p('“r is close to 1” means', 'C', ['strong cause', 'weak fit', 'strong linear association', 'the slope is 1'], 'r measures linear association strength.')]),
  L(62, 'math', 'Data Analysis', 'Two-way tables', ['two-way table', 'conditional probability', 'relative frequency'], '30 students: 18 play a sport. 12 of those 18 also play music. What fraction of athletes play music?',
    ['A two-way table counts two categories at once.', 'A joint count is one cell. A marginal count is a row or column total.', 'A conditional percent uses the given group as the denominator.'],
    ['The word “of” names the denominator: of athletes, of seniors, of the whole school.'],
    [p('Fraction of athletes who play music?', 'A', ['12/18', '12/30', '18/30', '12/12'], 'Given athlete, so 18 is the whole.'), p('Fraction of all students who do both?', 'B', ['12/18', '12/30', '18/30', '8/30'], 'Both is 12 out of 30.'), p('If 8 students do neither, students who do exactly one are', 'C', ['10', '12', '10', '22'], '30-12-8=10.')]),
  L(63, 'math', 'Data Analysis', 'Basic probability', ['probability', 'favorable outcomes'], 'A fair die is rolled. P(rolling a 5)?',
    ['P = favorable / total equally likely outcomes.', 'P is always between 0 and 1.', 'The complement is 1 minus P.'],
    ['Count carefully. “At least one” is often easier as 1 minus none.'],
    [p('P(rolling a 5) on a fair die?', 'A', ['1/6', '5/6', '1/5', '1/2'], 'One face out of six.'), p('P(even) on a fair die?', 'B', ['1/6', '1/2', '1/3', '2/3'], '2, 4, 6.'), p('P(not a 5) is', 'C', ['1/6', '5/5', '5/6', '0'], '1 - 1/6 = 5/6.')]),
  L(64, 'math', 'Data Analysis', 'Compound probability', ['compound probability', 'independent', 'and/or'], 'A coin and a die. P(heads and a 6)?',
    ['Independent “and” multiplies the probabilities.', 'Mutually exclusive “or” adds the probabilities.', 'If events can both happen, P(A or B)=P(A)+P(B)-P(both).'],
    ['Ask: can both happen at once? If no, just add.'],
    [p('P(heads and a 6)?', 'A', ['1/12', '1/2', '1/6', '2/3'], '(1/2)(1/6)=1/12.'), p('P(heads or tails) on one flip?', 'B', ['1/2', '1', '0', '1/4'], 'Those two cover every flip.'), p('P(red or face card) needs', 'C', ['only add', 'only multiply', 'add, then subtract the overlap', 'subtract only'], 'Some cards are both red and face cards.')]),
  L(65, 'math', 'Data Analysis', 'Combinations and permutations', ['combination', 'permutation', 'nCr', 'nPr'], 'How many ways to choose 2 books from 5 if order does not matter?',
    ['Permutations: order matters. Combinations: order does not.', 'nPr = n! / (n-r)!. nCr = n! / (r!(n-r)!).', 'A lineup is a permutation. A committee is a combination.'],
    ['In Desmos, nCr(5,2) and nPr(5,2) are built-in.'],
    [p('Choose 2 books from 5, order ignored?', 'A', ['10', '20', '5', '25'], '5C2=10.'), p('Arrange 3 of 5 books on a shelf?', 'B', ['10', '60', '15', '125'], '5P3=60.'), p('5! equals', 'C', ['25', '60', '120', '5'], '5x4x3x2x1=120.')]),
  L(66, 'math', 'Data Analysis', 'Expected value', ['expected value', 'weighted average'], 'A game pays $10 with P=0.2 and $0 otherwise. What is the expected payout?',
    ['Expected value is the long-run average: sum of (value x probability).', 'It does not have to be a value you can actually win on one play.', 'If the ticket costs more than the expected payout, the game is against you.'],
    ['Make a two-column list: outcome, probability, then multiply and add.'],
    [p('Expected payout if $10 with P=0.2 else $0?', 'A', ['$2', '$10', '$8', '$0.2'], '10x0.2 + 0x0.8 = 2.'), p('A spinner: 4, 4, and 10, equally likely. Expected value?', 'B', ['6', '6', '4', '18'], '(4+4+10)/3=6.'), p('Pay $3 to play the $10/0.2 game. Expected profit?', 'C', ['$2', '$3', '-$1', '$7'], '2 - 3 = -1.')]),
  L(67, 'math', 'Data Analysis', 'Statistical claims', ['sample', 'margin of error', 'survey'], 'A poll of 400 voters has margin of error 5%. The estimate is 48%. What interval is reported?',
    ['A sample estimates a population. It is not a census.', 'Margin of error makes an interval around the estimate.', 'Bigger random samples usually shrink the margin of error.'],
    ['If the interval contains 50%, you cannot claim a lead.'],
    [p('48% with 5% margin of error is the interval', 'A', ['43% to 53%', '48% to 53%', '5% to 48%', '43% to 48%'], '48±5.'), p('Why not claim a majority?', 'B', ['48 is less than 50, and 50 sits in the interval', 'the sample is random', '400 is too big', 'percents cannot exceed 50'], 'The interval crosses 50.'), p('A volunteer web poll is weakest because of', 'C', ['a huge sample', 'random assignment', 'voluntary response bias', 'a small margin'], 'Who chooses to answer is not a random sample.')]),
  L(68, 'math', 'Data Analysis', 'Center vs spread', ['standard deviation', 'spread', 'center'], 'Which set is more spread out: 10,10,10 or 1,10,19?',
    ['Center is a typical value: mean or median.', 'Spread is how far values sit from that center: range, IQR, or standard deviation.', 'Adding the same number to every value moves the center but leaves spread the same.'],
    ['Standard deviation 0 means every value is identical.'],
    [p('Which set is more spread out?', 'A', ['1, 10, 19', '10, 10, 10', 'they match', 'cannot tell'], 'The first is identical, the second stretches.'), p('Add 5 to every value. Standard deviation', 'B', ['grows by 5', 'stays the same', 'becomes 0', 'doubles'], 'Shifts do not change spread.'), p('Double every value. The mean', 'C', ['stays', 'halves', 'doubles', 'drops to 0'], 'Every number scales, so the center scales.')]),
  L(69, 'math', 'Geometry', 'Angle relationships', ['vertical angles', 'corresponding angles', 'parallel lines'], 'Two lines cross. One angle is 70. What is the vertical angle?',
    ['Vertical angles are equal. Adjacent angles on a line add to 180.', 'If a transversal cuts parallel lines, corresponding angles are equal.', 'Alternate interior angles are equal too.'],
    ['Mark the parallel arrows before you chase angles.'],
    [p('Vertical angle to 70 is', 'A', ['70', '110', '20', '90'], 'Vertical angles match.'), p('Adjacent angle on a straight line to 70 is', 'B', ['70', '110', '20', '140'], '180-70=110.'), p('A transversal hits parallel lines. A corresponding angle to 70 is', 'C', ['110', '20', '70', '180'], 'Corresponding angles are equal.')]),
  L(70, 'math', 'Geometry', 'Similar triangles', ['similar triangles', 'aa similarity', 'scale factor'], 'Two triangles are similar with scale 2/3. If a small side is 6, the matching large side is?',
    ['Similar triangles have equal angles and proportional sides.', 'Match vertices in the same order.', 'Scale factor is new/old for the sides you are comparing.'],
    ['Write a proportion with matching sides in the same position.'],
    [p('Scale 2/3, small side 6. Matching large side?', 'A', ['9', '4', '12', '3'], '6 / (2/3) wait: if small/large=2/3, large=6*(3/2)=9.'), p('Angles of a similar copy of 40-60-80 are', 'B', ['40-60-80', '80-100-120', '20-30-40', 'different'], 'Same angles.'), p('If sides are 5, 10 and the small matching side is 4, the other is', 'C', ['2', '8', '8', '20'], '5/10=4/x, x=8.')]),
  L(71, 'math', 'Geometry', 'Congruent triangles', ['congruent', 'sas', 'asa', 'sss'], 'What does SAS tell you?',
    ['Congruent triangles are the same size and shape.', 'SSS, SAS, ASA, and AAS prove congruence. AAA does not.', 'Corresponding parts of congruent triangles are equal.'],
    ['SSA is not a valid shortcut on the SAT/ACT.'],
    [p('SAS means', 'A', ['two sides and the included angle match', 'all angles match', 'three angles match', 'one side matches'], 'The angle must sit between the two sides.'), p('AAA proves', 'B', ['congruence', 'similarity only', 'nothing', 'area equality'], 'Same shape, not necessarily same size.'), p('If triangle ABC is congruent to DEF, angle B equals', 'C', ['D', 'F', 'E', 'A'], 'Second letter matches second letter.')]),
  L(72, 'math', 'Geometry', 'Special right triangles', ['45-45-90', '30-60-90'], 'In a 45-45-90 triangle the legs are 5. What is the hypotenuse?',
    ['45-45-90: legs x, x; hypotenuse x√2.', '30-60-90: opposite 30 is x, opposite 60 is x√3, hypotenuse 2x.', 'These appear constantly on SAT geometry.'],
    ['If you see √2 or √3 in the choices, check a special right triangle.'],
    [p('45-45-90 legs 5. Hypotenuse?', 'A', ['5√2', '10', '5√3', '2.5'], 'x√2.'), p('30-60-90 hypotenuse 10. Side opposite 30?', 'B', ['10√3', '5', '5√3', '20'], 'Half the hypotenuse.'), p('30-60-90 short leg 4. Side opposite 60?', 'C', ['4', '8', '4√3', '8√3'], 'x√3 = 4√3.')]),
  L(73, 'math', 'Geometry', 'Right triangle trigonometry', ['sine', 'cosine', 'tangent', 'sohcahtoa'], 'In a right triangle, opposite 8 and hypotenuse 17. What is sin θ?',
    ['sin = opposite / hypotenuse. cos = adjacent / hypotenuse. tan = opposite / adjacent.', 'Set Desmos to degree mode on SAT/ACT angle items.', 'If you know two sides, the third is Pythagorean.'],
    ['Label opposite and adjacent from the angle in the question, not from the other acute angle.'],
    [p('Opposite 8, hypotenuse 17. sin θ?', 'A', ['8/17', '15/17', '8/15', '17/8'], 'SOH.'), p('Adjacent 15, hypotenuse 17. cos θ?', 'B', ['8/17', '15/17', '15/8', '8/15'], 'CAH.'), p('tan θ for opposite 8, adjacent 15 is', 'C', ['15/8', '8/17', '8/15', '17/15'], 'TOA.')]),
  L(74, 'math', 'Geometry', 'Law of sines', ['law of sines', 'aas', 'asa'], 'In triangle ABC, a/sin A = b/sin B.',
    ['a / sin A = b / sin B = c / sin C.', 'Use this when you have a side and its opposite angle, plus one more piece.', 'Watch the ambiguous SSA case on ACT: two triangles can exist.'],
    ['Cross multiply after you write the two-fraction proportion.'],
    [p('Law of sines says', 'A', ['a/sin A = b/sin B', 'a/sin B = b/sin A', 'a+b=c', 'sin A = a/b'], 'Side over opposite sine.'), p('A=30, a=5, B=60. b equals', 'B', ['5√3', '5√3', '10', '5/2'], '5/sin30 = b/sin60, 5/0.5 = b/(√3/2), b=5√3.'), p('You need law of sines when you have', 'C', ['SSS only', 'three sides and no angle', 'an angle and its opposite side', 'right triangle legs only'], 'AAS or ASA, or SSA carefully.')]),
  L(75, 'math', 'Geometry', 'Law of cosines', ['law of cosines', 'sas', 'sss'], 'c^2 = a^2 + b^2 - 2ab cos C.',
    ['Law of cosines generalizes Pythagoras when the included angle is not 90.', 'Use SAS to find the third side, or SSS to find an angle.', 'If C=90, cos 90=0 and you recover a^2+b^2=c^2.'],
    ['Keep the minus sign. Students drop it and get a huge side.'],
    [p('If C=90, law of cosines becomes', 'A', ['Pythagorean theorem', 'law of sines', 'c=a+b', 'area formula'], 'cos 90 = 0.'), p('Sides 3 and 4 with included 60 degrees. c^2 =', 'B', ['25', '13', '7', '12'], '9+16-2*3*4*0.5=25-12=13.'), p('Law of cosines is the move for', 'C', ['ASA', 'two sides and a non-included angle only', 'SSS or SAS', 'vertical angles'], 'You need two sides and the included angle, or three sides.')]),
  L(76, 'math', 'Geometry', 'Area of polygons', ['area', 'triangle area', 'trapezoid'], 'Area of a triangle is (1/2)bh.',
    ['Rectangle A=lw. Triangle A=(1/2)bh. Parallelogram A=bh. Trapezoid A=(1/2)(b1+b2)h.', 'Height is perpendicular to the base, not a slanted side.', 'Same base and height means same triangle area.'],
    ['If the question gives two sides and an included angle, A=(1/2)ab sin C.'],
    [p('Triangle base 10, height 6. Area?', 'A', ['30', '60', '16', '32'], '(1/2)*10*6=30.'), p('Trapezoid bases 4 and 10, height 3. Area?', 'B', ['21', '21', '42', '17'], '(1/2)(14)(3)=21.'), p('Rectangle 8 by 5. Area?', 'C', ['13', '26', '40', '80'], '8x5=40.')]),
  L(77, 'math', 'Geometry', 'Circles: area and circumference', ['circle', 'circumference', 'pi'], 'A circle has radius 4. What is the area?',
    ['Area = πr^2. Circumference = 2πr = πd.', 'Diameter is twice the radius.', 'Leave answers in terms of π unless the question asks for a decimal.'],
    ['If you are given circumference, divide by 2π to get r, then find area.'],
    [p('Radius 4. Area?', 'A', ['16π', '8π', '4π', '32π'], 'π*16.'), p('Radius 4. Circumference?', 'B', ['16π', '8π', '4π', '2π'], '2π*4=8π.'), p('Circumference 10π. Radius?', 'C', ['10', '5π', '5', '20'], '2πr=10π, r=5.')]),
  L(78, 'math', 'Geometry', 'Arcs and sectors', ['arc length', 'sector', 'central angle'], 'A 90 degree arc in a circle of radius 6. What is the arc length?',
    ['Arc length = (θ/360)*2πr.', 'Sector area = (θ/360)*πr^2.', 'θ must be the central angle.'],
    ['90/360 is 1/4, so you are taking one fourth of the full circle.'],
    [p('90 degree arc, r=6. Arc length?', 'A', ['3π', '9π', '6π', '12π'], '(90/360)*12π=3π.'), p('Same circle, 90 degree sector area?', 'B', ['9π', '9π', '36π', '3π'], '(1/4)*36π=9π.'), p('A 60 degree arc with r=9. Length?', 'C', ['3π', '6π', '3π', '9π'], '(60/360)*18π=3π.')]),
  L(79, 'math', 'Geometry', 'Circle equations', ['circle equation', 'center radius form'], '(x-2)^2 + (y+3)^2 = 16. Center and radius?',
    ['(x-h)^2 + (y-k)^2 = r^2 has center (h, k) and radius r.', '(y+3) means k = -3.', 'If the equation is expanded, complete the square on x and on y.'],
    ['In Desmos, type the equation and the circle appears. Read center and a point on the rim.'],
    [p('Center of (x-2)^2+(y+3)^2=16?', 'A', ['(2, -3)', '(-2, 3)', '(2, 3)', '(-2, -3)'], 'h=2, k=-3.'), p('Radius is', 'B', ['16', '4', '8', '2'], 'r^2=16, r=4.'), p('A point on the circle is', 'C', ['(2, -3)', '(6, -3)', '(2, 1)', '(2, 13)'], 'Center plus 4 in the x direction: (6,-3).')]),
  L(80, 'math', 'Geometry', 'Volume', ['volume', 'cylinder', 'sphere', 'prism'], 'Volume of a rectangular box 3 by 4 by 5?',
    ['Prism or box: V = lwh. Cylinder: V = πr^2 h. Sphere: V = (4/3)πr^3. Cone/pyramid: (1/3) base area times height.', 'Volume is cubic units.', 'If you scale every length by k, volume scales by k^3.'],
    ['The SAT reference sheet lists several of these. Still know which formula is which.'],
    [p('Box 3 by 4 by 5. Volume?', 'A', ['60', '12', '47', '30'], '3x4x5=60.'), p('Cylinder r=2, h=5. Volume?', 'B', ['10π', '20π', '4π', '40π'], 'π*4*5=20π.'), p('Sphere r=3. Volume?', 'C', ['36π', '12π', '36π', '27π'], '(4/3)π*27=36π.')]),
  L(81, 'math', 'Geometry', 'Surface area', ['surface area', 'net'], 'Surface area of a cube with edge 3?',
    ['Surface area adds the areas of every face.', 'A cube has 6 square faces. A cylinder has two circles plus a rectangle 2πr by h.', 'A net helps you see every face once.'],
    ['Do not mix surface area with volume. One is wrapping, one is filling.'],
    [p('Cube edge 3. Surface area?', 'A', ['54', '27', '18', '9'], '6*9=54.'), p('Cube edge 3. Volume?', 'B', ['54', '27', '9', '12'], '3^3=27.'), p('Cylinder r=2, h=3. Lateral area (no bases)?', 'C', ['4π', '12π', '12π', '2π'], '2πrh=12π.')]),
  L(82, 'math', 'Geometry', 'Coordinate geometry', ['midpoint', 'distance', 'coordinate plane'], 'Midpoint of (2, 4) and (6, 10)?',
    ['Midpoint averages the x-values and averages the y-values.', 'Distance is √((x2-x1)^2 + (y2-y1)^2).', 'A vertical segment has undefined slope and length |y2-y1|.'],
    ['In Desmos, plot the two points and the segment. Read the midpoint tool or average by hand.'],
    [p('Midpoint of (2, 4) and (6, 10)?', 'A', ['(4, 7)', '(8, 14)', '(4, 6)', '(3, 7)'], 'Averages 4 and 7.'), p('Distance from (0, 0) to (3, 4)?', 'B', ['5', '5', '7', '12'], '3-4-5 triangle.'), p('Distance from (1, 2) to (1, 8)?', 'C', ['9', '7', '6', '√40'], 'Same x, so |8-2|=6.')]),
  L(83, 'math', 'Geometry', 'Transformations', ['translation', 'reflection', 'rotation', 'dilation'], 'Point (3, 2) reflected over the x-axis is?',
    ['Translation slides. Reflection flips. Rotation turns. Dilation scales from a center.', 'Reflect over x-axis: (x, y) → (x, -y). Over y-axis: (x, y) → (-x, y).', 'A dilation by k from the origin multiplies both coordinates by k.'],
    ['Write the rule first, then plug the point.'],
    [p('(3, 2) over the x-axis?', 'A', ['(3, -2)', '(-3, 2)', '(-3, -2)', '(2, 3)'], 'y sign flips.'), p('(3, 2) translated by <-1, 4> is', 'B', ['(2, 6)', '(2, 6)', '(4, -2)', '(3, 6)'], '3-1=2, 2+4=6.'), p('(3, 2) dilated by 2 from the origin is', 'C', ['(5, 4)', '(6, 2)', '(6, 4)', '(1.5, 1)'], 'Multiply both by 2.')]),
  L(84, 'math', 'Geometry', 'Similar solids and scale', ['scale factor', 'similar solids', 'volume scale'], 'Two similar cubes. Side scale 2. How do volumes compare?',
    ['Linear scale k. Area scale k^2. Volume scale k^3.', 'If sides double, surface area times 4, volume times 8.', 'This is a favorite SAT hard-easy item.'],
    ['Decide whether the question is asking length, area, or volume before you raise k to a power.'],
    [p('Side scale 2. Volume scale?', 'A', ['8', '4', '2', '6'], '2^3=8.'), p('Side scale 3. Area scale?', 'B', ['9', '9', '27', '6'], '3^2=9.'), p('Volume scale 8. Side scale?', 'C', ['8', '4', '2', '64'], 'Cube root of 8 is 2.')]),
  L(85, 'math', 'Geometry', 'Density', ['density', 'mass', 'volume density'], 'Density = mass / volume. Mass 20 g, volume 4 cm^3. Density?',
    ['density = mass / volume.', 'If density is constant, mass scales with volume.', 'A SAT “population density” item is people / area, same structure.'],
    ['Keep the units. 5 g/cm^3 is not 5 cm^3/g.'],
    [p('Mass 20 g, volume 4 cm^3. Density?', 'A', ['5 g/cm^3', '80 g/cm^3', '16 g/cm^3', '0.2 g/cm^3'], '20/4=5.'), p('Density 3, volume 10. Mass?', 'B', ['13', '30', '3.3', '7'], '3x10=30.'), p('800 people on 2 km^2. People per km^2?', 'C', ['400', '1600', '400', '802'], '800/2=400.')]),
  L(86, 'math', 'ACT Extra', 'Logarithms', ['logarithm', 'log', 'change of base'], 'log_2 8 = ?',
    ['log_b a = c means b^c = a.', 'log_b (xy) = log_b x + log_b y. log_b (x/y) = log_b x - log_b y.', 'log_b (x^k) = k log_b x. log_b b = 1. log_b 1 = 0.'],
    ['Rewrite the log as an exponent if the numbers are small and friendly.'],
    [p('log_2 8 equals', 'A', ['3', '4', '16', '1/3'], '2^3=8.'), p('log_10 1000 equals', 'B', ['2', '3', '100', '1/3'], '10^3=1000.'), p('log_3 9 + log_3 3 equals', 'C', ['2', '1', '3', '9'], '2+1=3, or log_3 27=3.')]),
  L(87, 'math', 'ACT Extra', 'Matrices', ['matrix', 'determinant', 'matrix multiply'], 'What is the determinant of [[2, 3], [1, 4]]?',
    ['A 2x2 determinant ad-bc.', 'Add matrices entrywise. Multiply a matrix by a scalar on every entry.', 'Matrix multiplication is row-by-column and is not commutative.'],
    ['ACT usually stays at 2x2 determinants and simple arithmetic.'],
    [p('det [[2,3],[1,4]]?', 'A', ['5', '8', '11', '-1'], '8-3=5.'), p('[[1,2]] + [[3,4]] equals', 'B', ['[[4,6]]', '[[4,6]]', '[[3,8]]', '[[1,2,3,4]]'], 'Add matching entries.'), p('2[[1,0],[0,1]] equals', 'C', ['[[1,0],[0,1]]', '[[2,2],[2,2]]', '[[2,0],[0,2]]', '[[2,1],[1,2]]'], 'Scale the identity.')]),
  L(88, 'math', 'ACT Extra', 'Degrees and radians', ['radian', 'degrees', 'unit circle'], 'Convert 180 degrees to radians.',
    ['radians = degrees · π/180. degrees = radians · 180/π.', 'π radians = 180 degrees. 2π is a full turn.', 'SAT/ACT trig items in Desmos need degree mode unless the problem uses π.'],
    ['A common conversion: 30°=π/6, 45°=π/4, 60°=π/3, 90°=π/2.'],
    [p('180 degrees in radians is', 'A', ['π', '2π', 'π/2', '180π'], '180 · π/180 = π.'), p('π/2 radians in degrees is', 'B', ['45', '90', '180', '60'], 'Quarter turn.'), p('30 degrees in radians is', 'C', ['π/2', 'π/3', 'π/6', 'π/4'], '30/180 = 1/6, so π/6.')]),
  L(89, 'math', 'ACT Extra', 'Trig identities', ['trig identity', 'sin^2+cos^2', 'reciprocal'], 'sin^2 θ + cos^2 θ = ?',
    ['sin^2 θ + cos^2 θ = 1.', 'tan θ = sin θ / cos θ. csc = 1/sin, sec = 1/cos, cot = 1/tan.', 'If you know sin and the quadrant, you can get cos from the identity.'],
    ['On ACT, rewrite everything in sin and cos when an expression looks stuck.'],
    [p('sin^2 θ + cos^2 θ equals', 'A', ['1', '0', '2', 'sin 2θ'], 'Pythagorean identity.'), p('If sin θ = 3/5 and θ is acute, cos θ is', 'B', ['4/5', '4/5', '5/3', '3/4'], '3-4-5 triangle.'), p('tan θ when sin=3/5 and cos=4/5 is', 'C', ['12/25', '5/4', '3/4', '4/3'], 'sin/cos=3/4.')]),
  L(90, 'math', 'ACT Extra', 'Direct and inverse variation', ['direct variation', 'inverse variation', 'constant of variation'], 'y varies directly with x, and y=12 when x=3. What is y when x=5?',
    ['Direct: y = kx. Inverse: y = k/x.', 'Find k from the given pair, then evaluate at the new x.', '“Varies jointly” multiplies more than one variable.'],
    ['If x doubles and the relation is inverse, y halves.'],
    [p('Direct, y=12 when x=3. k is', 'A', ['4', '36', '15', '9'], '12=3k, k=4.'), p('Then y when x=5 is', 'B', ['20', '20', '12/5', '60'], 'y=4*5=20.'), p('Inverse, y=8 when x=2. y when x=4 is', 'C', ['16', '4', '4', '2'], 'k=16, y=16/4=4.')]),
  L(91, 'math', 'ACT Extra', 'Work-rate problems', ['work rate', 'combined work', 'pipes'], 'A can finish a job in 6 hours, B in 3. How long together?',
    ['Rate is 1/time for one complete job.', 'Add rates: 1/6 + 1/3 = 1/t.', 'Together they finish faster than either person alone.'],
    ['The LCD of the times is the fastest clean way to add the fractions.'],
    [p('A in 6 hours. A’s rate is', 'A', ['1/6 job per hour', '6 jobs per hour', '1/3', '6'], 'One job in 6 hours.'), p('B in 3 hours. Combined rate is', 'B', ['1/2', '1/2', '1/9', '1/3'], '1/6+2/6=1/2.'), p('Time together is', 'C', ['4.5 hours', '9 hours', '2 hours', '3 hours'], '1 / (1/2) = 2 hours.')]),
  L(92, 'math', 'ACT Extra', 'Midpoint and distance formulas', ['midpoint formula', 'distance formula'], 'Find the midpoint and the length of the segment from (-1, 2) to (5, 10).',
    ['Midpoint: ((x1+x2)/2, (y1+y2)/2).', 'Distance: √((x2-x1)^2+(y2-y1)^2).', 'These two formulas are the coordinate versions of “halfway” and “how far.”'],
    ['Plot first. A 6-by-8 run is a 10 hypotenuse.'],
    [p('Midpoint of (-1, 2) and (5, 10)?', 'A', ['(2, 6)', '(4, 8)', '(2, 12)', '(3, 6)'], 'Averages 2 and 6.'), p('Horizontal change is', 'B', ['6', '6', '8', '4'], '5-(-1)=6.'), p('Distance is', 'C', ['10', '14', '10', '√14'], '6-8-10 triple.')]),
]

