import type { DesmosStrategy } from './types'

function id(n: number): string {
  return `e2000000-0000-0000-0000-0000000000${String(n).padStart(2, '0')}`
}

const SAT_ACT_ALGEBRA = [
  { test: 'SAT' as const, topic: 'Linear Equations' },
  { test: 'SAT' as const, topic: 'Linear Functions' },
  { test: 'SAT' as const, topic: 'Systems of Equations' },
  { test: 'ACT' as const, topic: 'Linear Equations' },
  { test: 'ACT' as const, topic: 'Systems of Equations' },
]

export const DESMOS_STRATEGIES: DesmosStrategy[] = [
  {
    id: id(1),
    slug: 'systems_intersection',
    title: 'Solve a system by graphing the intersection',
    category: 'algebra',
    mode: 'desmos_first',
    description: 'When two equations must be true at the same time, their shared solution is the point where the graphs cross.',
    when_to_use: 'The question gives two equations in x and y (or two expressions set equal in a system) and asks for the solution, the x-value, the y-value, or the intersection point.',
    when_not_to_use: 'Skip this when one equation is a one-step mental solve, or when the question only asks what a variable represents in words.',
    recognition_rule: 'Two equations + same solution → INTERSECTION.',
    desmos_capability: 'Graph two expressions and read the gray intersection point of interest.',
    desmos_input_template: ['y = ...', 'y = ...'],
    student_steps: [
      'Rewrite each equation as y = ... if it is not already.',
      'Enter both lines in Desmos.',
      'Tap a curve, then tap the intersection point and read the coordinates.',
    ],
    what_to_look_for: 'The intersection point (x, y). That pair is the only coordinate that sits on both graphs.',
    why_it_works: 'A graph is every pair that satisfies one equation. The crossing is the pair that satisfies both, which is the definition of a system solution.',
    common_mistakes: [
      'Reading an intercept instead of the crossing.',
      'Forgetting to isolate y, so Desmos graphs the wrong relation.',
      'Using the x-value when the question asked for y, or the reverse.',
    ],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'easy',
    desmos_only_possible: true,
    desmos_first_recommended: true,
    hybrid_recommended: false,
    estimated_time_savings: 'Turns 60–90s of substitution into about 15s.',
    example_problem: 'What is the solution to the system y = 2x + 5 and y = -x + 11?',
    example_desmos_input: ['y=2x+5', 'y=-x+11'],
    example_result: 'The graphs cross at (2, 9), so x = 2 and y = 9.',
    explanation: 'Both equations describe a line. The one coordinate that is on both lines is (2, 9). Check: 2(2)+5=9 and -2+11=9.',
    try_it_prompt: 'Solve 2x - y = 10 and 6y = 12x + 36 by graphing. What do you notice about the lines?',
    keywords: ['system', 'intersection', 'two equations', 'simultaneous', 'solution of the system'],
    source_reference: ['Getting Started_ Desmos Graphing Calculator.pdf'],
    topic_keys: SAT_ACT_ALGEBRA,
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'plotExpressions', latex: ['y=2x+5', 'y=-x+11'] },
      { type: 'setViewport', bounds: { left: -4, right: 8, bottom: -2, top: 14 } },
      { type: 'addPoint', x: 2, y: 9, label: 'solution' },
    ],
    approved: true,
  },
  {
    id: id(2),
    slug: 'equation_both_sides',
    title: 'Solve an equation by graphing each side',
    category: 'algebra',
    mode: 'desmos_first',
    description: 'Any equation A = B can be treated as two graphs, y = A and y = B. Their intersection x-value is the solution.',
    when_to_use: 'One equation that is messy to isolate, especially with fractions, a quadratic on one side, or two different function forms.',
    when_not_to_use: 'Do not graph both sides of 3x + 1 = 10. That is faster in your head.',
    recognition_rule: 'Two sides of an equation → graph each side and INTERSECT.',
    desmos_capability: 'Plot y = left side and y = right side, then read the intersection x-coordinate.',
    desmos_input_template: ['y = left side', 'y = right side'],
    student_steps: [
      'Put the left side on one line as y = ...',
      'Put the right side on the next line as y = ...',
      'Read the x-coordinate of the intersection. That x solves the equation.',
    ],
    what_to_look_for: 'The x-value of the intersection. Use y only if the question asks for the shared output.',
    why_it_works: 'At the crossing, both sides produce the same y, so left = right.',
    common_mistakes: [
      'Reporting the y-coordinate when the question asked for x.',
      'Moving all terms to one side and then graphing only y = 0 when both-sides is clearer.',
    ],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'medium',
    desmos_only_possible: true,
    desmos_first_recommended: true,
    hybrid_recommended: false,
    estimated_time_savings: 'Saves the algebra on fraction or mixed-form equations.',
    example_problem: 'Solve (2x)/3 - x/6 = 4.',
    example_desmos_input: ['y=(2x)/3-x/6', 'y=4'],
    example_result: 'They meet at x = 8.',
    explanation: 'The horizontal line y = 4 is the right side. The other curve is the left side. They share an output only at x = 8.',
    try_it_prompt: 'Graph both sides of 3x/4 - x/2 = 5. What x do you get?',
    keywords: ['solve', 'equation', 'both sides', 'equals', 'find x'],
    source_reference: ['Getting Started_ Desmos Graphing Calculator.pdf', 'Functions – Desmos Help Center.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Linear Equations' },
      { test: 'SAT', topic: 'Nonlinear Equations' },
      { test: 'SAT', topic: 'Rational Expressions' },
      { test: 'ACT', topic: 'Linear Equations' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'plotExpressions', latex: ['y=(2x)/3-x/6', 'y=4'] },
      { type: 'setViewport', bounds: { left: -2, right: 12, bottom: -2, top: 10 } },
    ],
    approved: true,
  },
  {
    id: id(3),
    slug: 'quadratic_zeros',
    title: 'Find quadratic solutions from x-intercepts',
    category: 'advanced_math',
    mode: 'desmos_first',
    description: 'Solutions to ax^2 + bx + c = 0 are the places the parabola crosses the x-axis.',
    when_to_use: 'The question asks for solutions, roots, zeros, or x-intercepts of a quadratic or other polynomial.',
    when_not_to_use: 'If the quadratic is already factored and the question is conceptual (how many real roots), you may not need the graph.',
    recognition_rule: 'Equation = 0 → ROOTS / x-intercepts.',
    desmos_capability: 'Graph y = the expression. Gray points of interest mark the intercepts.',
    desmos_input_template: ['y = ax^2 + bx + c'],
    student_steps: [
      'Enter y = the quadratic (or move every term to one side first).',
      'Click the curve.',
      'Read the x-intercepts. Those x-values are the solutions.',
    ],
    what_to_look_for: 'Where the graph touches or crosses the x-axis.',
    why_it_works: 'An x-intercept means y = 0, which is exactly the equation you were solving.',
    common_mistakes: [
      'Giving the vertex instead of the intercepts.',
      'Missing a double root that only touches the axis once.',
    ],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'easy',
    desmos_only_possible: true,
    desmos_first_recommended: true,
    hybrid_recommended: false,
    estimated_time_savings: 'Avoids factoring or the quadratic formula when the graph is clean.',
    example_problem: 'What are the solutions of x^2 - 5x + 4 = 0?',
    example_desmos_input: ['y=x^2-5x+4'],
    example_result: 'x-intercepts at 1 and 4.',
    explanation: 'The parabola hits the x-axis at 1 and 4, so those inputs make the expression zero.',
    try_it_prompt: 'Graph y = x^2 - x - 6 and name the zeros.',
    keywords: ['quadratic', 'roots', 'zeros', 'solutions', 'x-intercept', 'factor'],
    source_reference: ['Getting Started_ Desmos Graphing Calculator.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Quadratics' },
      { test: 'SAT', topic: 'Polynomials' },
      { test: 'SAT', topic: 'Nonlinear Equations' },
      { test: 'ACT', topic: 'Quadratic Functions' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'addExpression', latex: 'y=x^2-5x+4', color: '#2f72dc' },
      { type: 'setViewport', bounds: { left: -2, right: 7, bottom: -4, top: 8 } },
    ],
    approved: true,
  },
  {
    id: id(4),
    slug: 'quadratic_vertex',
    title: 'Read a maximum or minimum from the vertex',
    category: 'advanced_math',
    mode: 'desmos_first',
    description: 'The highest or lowest point on a parabola is the vertex. Desmos marks it as a point of interest.',
    when_to_use: 'The question asks for a maximum, minimum, vertex, turning point, or the peak/lowest value of a quadratic model.',
    when_not_to_use: 'If it only asks for intercepts, do not stop at the vertex.',
    recognition_rule: 'Quadratic + maximum/minimum → VERTEX.',
    desmos_capability: 'Graph the quadratic and hover the gray vertex point.',
    desmos_input_template: ['y = ax^2 + bx + c'],
    student_steps: [
      'Graph the quadratic.',
      'Click the curve and find the lowest or highest gray point.',
      'The x-coordinate is when the max/min happens. The y-coordinate is the max/min value.',
    ],
    what_to_look_for: 'The vertex coordinates. Match x vs y to the wording of the question.',
    why_it_works: 'A parabola changes direction only once. That turning point is the extreme value of the function.',
    common_mistakes: [
      'Giving x when the question asked for the maximum value (y).',
      'Confusing vertex with an intercept.',
    ],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'easy',
    desmos_only_possible: true,
    desmos_first_recommended: true,
    hybrid_recommended: false,
    estimated_time_savings: 'Skips completing the square and vertex formula.',
    example_problem: 'A ball’s height is h(t) = -16t^2 + 48t + 4. What is the maximum height?',
    example_desmos_input: ['h=-16t^2+48t+4'],
    example_result: 'Vertex at (1.5, 40), so the maximum height is 40.',
    explanation: 'The parabola opens down. Its highest point is the vertex. The height is the y-value 40, not the time 1.5.',
    try_it_prompt: 'For y = x^2 - 6x + 5, is the vertex a max or a min, and what is that value?',
    keywords: ['maximum', 'minimum', 'vertex', 'highest', 'lowest', 'peak', 'turning point'],
    source_reference: ['Getting Started_ Desmos Graphing Calculator.pdf', 'Functions – Desmos Help Center.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Quadratics' },
      { test: 'SAT', topic: 'Functions' },
      { test: 'ACT', topic: 'Quadratic Functions' },
      { test: 'ACT', topic: 'Function Notation' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'addExpression', latex: 'y=-16x^2+48x+4', color: '#2f72dc' },
      { type: 'setViewport', bounds: { left: -1, right: 4, bottom: -5, top: 45 } },
      { type: 'addPoint', x: 1.5, y: 40, label: 'max' },
    ],
    approved: true,
  },
  {
    id: id(5),
    slug: 'evaluate_function_notation',
    title: 'Evaluate f(a) with function notation',
    category: 'functions',
    mode: 'desmos_first',
    description: 'Once f(x) is defined, typing f(3) asks Desmos for the output at that input.',
    when_to_use: 'The question defines a function and asks for f(a), g(2), or a specific input value.',
    when_not_to_use: 'If the input is a tiny mental substitution like f(0) on f(x)=x+1, do it in your head.',
    recognition_rule: 'Function + specific x → EVALUATE / table.',
    desmos_capability: 'Function notation evaluation and optional function tables.',
    desmos_input_template: ['f(x) = ...', 'f(a)'],
    student_steps: [
      'Type the function as f(x) = ...',
      'On a new line, type f(the number you need).',
      'Read the value Desmos computes.',
    ],
    what_to_look_for: 'The numeric output of f(a).',
    why_it_works: 'Function notation is a machine: drop in x, get out y. Desmos does that substitution exactly.',
    common_mistakes: [
      'Typing f = 3 instead of f(3).',
      'Evaluating the wrong function when both f and g are defined.',
    ],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'easy',
    desmos_only_possible: true,
    desmos_first_recommended: true,
    hybrid_recommended: false,
    estimated_time_savings: 'Useful when the rule is messy or you need several inputs.',
    example_problem: 'If f(x) = x^2 + 3x, what is f(3)?',
    example_desmos_input: ['f(x)=x^2+3x', 'f(3)'],
    example_result: 'f(3) = 18.',
    explanation: '3^2 + 3(3) = 9 + 9 = 18. Desmos is just performing that substitution.',
    try_it_prompt: 'Define g(x,y) = x^2 + 3y and evaluate g(10, 3).',
    keywords: ['f(x)', 'evaluate', 'function notation', 'g(x)', 'input', 'output'],
    source_reference: ['Functions – Desmos Help Center.pdf', 'Getting Started_ Desmos Graphing Calculator.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Functions' },
      { test: 'SAT', topic: 'Linear Functions' },
      { test: 'ACT', topic: 'Function Notation' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'addExpression', latex: 'f(x)=x^2+3x' },
      { type: 'addExpression', latex: 'f(3)' },
    ],
    approved: true,
  },
  {
    id: id(6),
    slug: 'function_table_values',
    title: 'Build a table to compare or evaluate values',
    category: 'functions',
    mode: 'desmos_first',
    description: 'A function table fills outputs for any inputs you type, and extra columns can compare two functions.',
    when_to_use: 'You need several outputs, want to compare f and g at the same x, or the question is easier with a table than a graph.',
    when_not_to_use: 'Do not build a table for a single easy evaluation.',
    recognition_rule: 'Several x-values or “which is greater” at given inputs → TABLE.',
    desmos_capability: 'Function tables, computed columns, and side-by-side function headings.',
    desmos_input_template: ['f(x) = ...', 'table with heading f(x1)'],
    student_steps: [
      'Define the function.',
      'Add a table (or convert the function to a table).',
      'Type the x-values you care about and read the computed outputs.',
    ],
    what_to_look_for: 'The filled output column, or which function’s column is larger at that row.',
    why_it_works: 'Each row is one input. A heading like f(x1) tells Desmos to compute the matching output automatically.',
    common_mistakes: [
      'Editing a gray computed cell — those values are locked because they are calculated.',
      'Forgetting that implicit or polar graphs cannot be turned into function tables.',
    ],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'easy',
    desmos_only_possible: true,
    desmos_first_recommended: true,
    hybrid_recommended: false,
    estimated_time_savings: 'Faster than plugging five inputs by hand.',
    example_problem: 'For f(x) = 2x + 1 and g(x) = x^2, which is larger at x = 3?',
    example_desmos_input: ['f(x)=2x+1', 'g(x)=x^2'],
    example_result: 'f(3) = 7 and g(3) = 9, so g is larger at x = 3.',
    explanation: 'A two-column function table at x = 3 shows both outputs at once so you can compare them.',
    try_it_prompt: 'Compare y = 3x and y = x^2 at x = 0, 2, and 4 using a table.',
    keywords: ['table', 'values', 'function table', 'compare functions', 'input output'],
    source_reference: ['Tables – Desmos Help Center.pdf', 'Functions – Desmos Help Center.pdf', 'Getting Started_ Desmos Graphing Calculator.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Functions' },
      { test: 'SAT', topic: 'Linear Functions' },
      { test: 'SAT', topic: 'Data Interpretation' },
      { test: 'ACT', topic: 'Function Notation' },
      { test: 'ACT', topic: 'Reading Graphs and Tables' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'addExpression', latex: 'f(x)=2x+1' },
      { type: 'addExpression', latex: 'g(x)=x^2' },
      { type: 'addTable', columns: [{ latex: 'x', values: ['0', '2', '3', '4'] }, { latex: 'f(x)', values: [] }, { latex: 'g(x)', values: [] }] },
    ],
    approved: true,
  },
  {
    id: id(7),
    slug: 'linear_intercepts',
    title: 'Read slope and intercepts from a graphed line',
    category: 'algebra',
    mode: 'desmos_first',
    description: 'Graph y = mx + b and use the labeled intercepts, or two clear points, to recover slope.',
    when_to_use: 'The question asks for intercepts, slope, or the equation of a line you can graph.',
    when_not_to_use: 'If the slope is sitting in the equation already, do not graph just to reread m.',
    recognition_rule: 'Line + intercept/slope question → GRAPH and read labeled points.',
    desmos_capability: 'Points of interest for intercepts; zoom/pan to read clean coordinates.',
    desmos_input_template: ['y = mx + b'],
    student_steps: [
      'Graph the line.',
      'Click it and read the x- and y-intercepts.',
      'Slope is rise/run between any two exact points, often the intercepts.',
    ],
    what_to_look_for: 'Gray intercept points and any second lattice point.',
    why_it_works: 'The y-intercept is where x = 0. The x-intercept is where y = 0. Slope is the constant rate between any two points on the line.',
    common_mistakes: ['Mixing up intercepts.', 'Using a zoomed-out pixel estimate instead of a labeled point.'],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'easy',
    desmos_only_possible: true,
    desmos_first_recommended: true,
    hybrid_recommended: false,
    estimated_time_savings: 'Helpful when the line is given in standard form.',
    example_problem: 'What is the y-intercept of 3x + 2y = 12?',
    example_desmos_input: ['3x+2y=12'],
    example_result: 'The graph crosses the y-axis at (0, 6).',
    explanation: 'When x = 0, 2y = 12 so y = 6. Desmos shows that intercept immediately even if you never isolate y.',
    try_it_prompt: 'Graph 4x - y = 8 and report both intercepts and the slope.',
    keywords: ['intercept', 'slope', 'y-intercept', 'x-intercept', 'rate of change', 'line'],
    source_reference: ['Getting Started_ Desmos Graphing Calculator.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Linear Equations' },
      { test: 'SAT', topic: 'Linear Functions' },
      { test: 'SAT', topic: 'Slope and Rate of Change' },
      { test: 'ACT', topic: 'Linear Equations' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'addExpression', latex: '3x+2y=12' },
      { type: 'setViewport', bounds: { left: -2, right: 6, bottom: -2, top: 8 } },
    ],
    approved: true,
  },
  {
    id: id(8),
    slug: 'graph_linear_inequality',
    title: 'Shade a linear inequality',
    category: 'algebra',
    mode: 'desmos_first',
    description: 'Desmos shades the solution region. Strict inequalities get a dotted boundary; ≤ and ≥ get a solid one.',
    when_to_use: 'The question is an inequality in two variables or asks which region is the solution set.',
    when_not_to_use: 'One-variable inequalities like 2x + 3 > 11 are usually faster on a number line in your head.',
    recognition_rule: 'Shaded region or ≤/≥ in x and y → INEQUALITY GRAPH.',
    desmos_capability: 'Inequality shading with dotted vs solid boundaries.',
    desmos_input_template: ['y ≥ mx + b'],
    student_steps: [
      'Type the inequality exactly, using ≤ ≥ < >.',
      'Look at the shaded side and whether the boundary is solid or dotted.',
      'Test a point in the shade if the question asks which region or which point works.',
    ],
    what_to_look_for: 'The shaded half-plane and the style of the boundary line.',
    why_it_works: 'Every point in the shade makes the inequality true. The boundary is included only when the inequality is not strict.',
    common_mistakes: [
      'Treating a dotted line as included.',
      'Shading the wrong side after rewriting the inequality.',
    ],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'medium',
    desmos_only_possible: true,
    desmos_first_recommended: true,
    hybrid_recommended: false,
    estimated_time_savings: 'Avoids picking test points by hand when the graph is allowed.',
    example_problem: 'Which region is the solution of y ≥ 2x + 1?',
    example_desmos_input: ['y>=2x+1'],
    example_result: 'Solid line y = 2x + 1, shade above the line.',
    explanation: 'Non-strict means the line is included (solid). y greater than the line means the shade sits above it.',
    try_it_prompt: 'Graph y < -x + 4. Is (0, 4) a solution?',
    keywords: ['inequality', 'shade', 'greater than', 'less than', 'half-plane', 'boundary'],
    source_reference: ['Inequalities and Restrictions – Desmos Help Center.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Linear Inequalities' },
      { test: 'SAT', topic: 'Systems of Inequalities' },
      { test: 'ACT', topic: 'Inequalities' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'addExpression', latex: 'y>=2x+1', color: '#2f72dc' },
      { type: 'setViewport', bounds: { left: -6, right: 6, bottom: -4, top: 8 } },
    ],
    approved: true,
  },
  {
    id: id(9),
    slug: 'systems_inequalities_overlap',
    title: 'Find the overlap of two inequalities',
    category: 'algebra',
    mode: 'desmos_first',
    description: 'Graph both inequalities. The solution is the region that is shaded twice.',
    when_to_use: 'A system of inequalities, or a question asking which point satisfies both constraints.',
    when_not_to_use: 'A single inequality, or a word problem that never gives graphable constraints.',
    recognition_rule: 'Two inequalities + “both true” → OVERLAP of the shades.',
    desmos_capability: 'Multiple inequality shades, plus optional { } restrictions with and/or.',
    desmos_input_template: ['y ≥ ...', 'y ≤ ...'],
    student_steps: [
      'Enter each inequality on its own line.',
      'Find the double-shaded region.',
      'If the question gives points, see which ones sit in that overlap (and on solid boundaries if included).',
    ],
    what_to_look_for: 'The overlapping shade, not just one inequality’s region.',
    why_it_works: 'A system requires every inequality at once. The overlap is the set of points that survive every constraint.',
    common_mistakes: [
      'Picking a point that works for only one inequality.',
      'Using or when the system needs and.',
    ],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'medium',
    desmos_only_possible: true,
    desmos_first_recommended: true,
    hybrid_recommended: false,
    estimated_time_savings: 'Faster than testing every answer choice through two inequalities.',
    example_problem: 'Which point satisfies y ≥ 2x + 1 and y ≤ -x + 8?',
    example_desmos_input: ['y>=2x+1', 'y<=-x+8'],
    example_result: 'The overlap is a wedge. (1, 5) sits in it; (1, 1) does not.',
    explanation: '5 ≥ 3 and 5 ≤ 7, so (1, 5) is in both shades.',
    try_it_prompt: 'Graph x^2 + y^2 ≤ 25 {x > 0 and y > 0}. What part of the disk remains?',
    keywords: ['system of inequalities', 'overlap', 'feasible region', 'both inequalities', 'constraints'],
    source_reference: ['Inequalities and Restrictions – Desmos Help Center.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Systems of Inequalities' },
      { test: 'SAT', topic: 'Linear Inequalities' },
      { test: 'ACT', topic: 'Inequalities' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'plotExpressions', latex: ['y>=2x+1', 'y<=-x+8'] },
      { type: 'setViewport', bounds: { left: -2, right: 8, bottom: -2, top: 10 } },
    ],
    approved: true,
  },
  {
    id: id(10),
    slug: 'domain_restriction_window',
    title: 'Limit a graph with curly-brace restrictions',
    category: 'functions',
    mode: 'hybrid',
    description: 'Add {min < x < max} to show only the piece of a graph the problem actually uses.',
    when_to_use: 'A piecewise rule, a limited domain, or a model that is only valid on an interval.',
    when_not_to_use: 'Do not restrict the domain just to zoom. Use the viewport for that.',
    recognition_rule: '“for x between” / piecewise / restricted domain → curly braces.',
    desmos_capability: 'Domain and range restrictions in curly brackets, plus and/or combinations.',
    desmos_input_template: ['y = f(x) {a ≤ x ≤ b}'],
    student_steps: [
      'Graph the full rule.',
      'Add a restriction such as {0 ≤ x ≤ 5}.',
      'Read intercepts or intersections only on the visible piece.',
    ],
    what_to_look_for: 'The remaining segment, and whether endpoints are included.',
    why_it_works: 'A restriction hides points that are not allowed. The visible graph is the model the question defined.',
    common_mistakes: [
      'Reading an intercept that exists on the unrestricted graph but not on the allowed interval.',
      'Using a comma instead of and/or inside the braces.',
    ],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'medium',
    desmos_only_possible: false,
    desmos_first_recommended: false,
    hybrid_recommended: true,
    estimated_time_savings: 'Prevents solving on the wrong piece of a piecewise function.',
    example_problem: 'f(x) = x - 1 for -2 ≤ x ≤ 2. What is f(2)?',
    example_desmos_input: ['y=x-1\\left\\{-2\\le x\\le2\\right\\}', 'f(2) if defined'],
    example_result: 'The segment runs from (-2, -3) to (2, 1), so f(2) = 1.',
    explanation: 'The brace keeps only x-values from -2 to 2. The endpoint x = 2 is allowed, and the output is 1.',
    try_it_prompt: 'Graph y = x^2 {1 ≤ y ≤ 5}. Which part of the parabola remains?',
    keywords: ['domain', 'restriction', 'piecewise', 'interval', 'for x between'],
    source_reference: ['Inequalities and Restrictions – Desmos Help Center.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Functions' },
      { test: 'SAT', topic: 'Linear Functions' },
      { test: 'ACT', topic: 'Function Notation' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'addExpression', latex: 'y=x-1\\left\\{-2\\le x\\le2\\right\\}' },
      { type: 'setViewport', bounds: { left: -5, right: 5, bottom: -5, top: 5 } },
    ],
    approved: true,
  },
  {
    id: id(11),
    slug: 'scatter_linear_regression',
    title: 'Fit a line to a scatterplot',
    category: 'data_analysis',
    mode: 'desmos_first',
    description: 'Put the data in a table, then run a linear regression to get slope, intercept, and r.',
    when_to_use: 'A table of paired data asks for the line of best fit, predicted value, slope, or correlation.',
    when_not_to_use: 'Two points only — just use the slope formula. Also skip if the question is only “which graph matches” and no calculation is needed.',
    recognition_rule: 'Dataset + line of best fit → TABLE + REGRESSION (~).',
    desmos_capability: 'Tables, Add Regression, and custom y1 ~ m x1 + b.',
    desmos_input_template: ['table of x1, y1', 'y1 ~ m x1 + b'],
    student_steps: [
      'Add a table and enter the pairs (or paste them).',
      'Use Zoom Fit so the cloud of points is visible.',
      'Add a linear regression, or type y1 ~ m x1 + b.',
      'Read m, b, and r. Export the equation if you need to predict.',
    ],
    what_to_look_for: 'The fitted line, the parameters m and b, and r if the question mentions correlation.',
    why_it_works: 'Regression chooses the line that minimizes the vertical residuals. Those parameters are the model the SAT/ACT wants you to use for predictions.',
    common_mistakes: [
      'Using = instead of ~, which does not fit parameters.',
      'Predicting far outside the data and treating it as exact.',
      'Mixing up r (linear only) with R².',
    ],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'medium',
    desmos_only_possible: true,
    desmos_first_recommended: true,
    hybrid_recommended: false,
    estimated_time_savings: 'Skips calculator-menu regression and hand residuals.',
    example_problem: 'Hours studied 1, 2, 4, 5 pair with scores 62, 68, 80, 86. What linear model predicts score from hours?',
    example_desmos_input: ['x1: 1,2,4,5', 'y1: 62,68,80,86', 'y1 ~ m x1 + b'],
    example_result: 'Approximately y = 6x + 56.',
    explanation: 'Each extra hour is associated with about 6 more points. The intercept 56 is the model’s score at 0 hours — a prediction, not a guaranteed fact.',
    try_it_prompt: 'Fit a line to (0, 3), (2, 7), (3, 8), (5, 13) and predict y when x = 4.',
    keywords: ['regression', 'line of best fit', 'scatter', 'correlation', 'predict', 'table of data'],
    source_reference: ['Regressions – Desmos Help Center.pdf', 'Tables – Desmos Help Center.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Statistics and Data' },
      { test: 'SAT', topic: 'Data Interpretation' },
      { test: 'SAT', topic: 'Slope and Rate of Change' },
      { test: 'ACT', topic: 'Statistics' },
      { test: 'ACT', topic: 'Trend Analysis' },
      { test: 'ACT', topic: 'Reading Graphs and Tables' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'addTable', columns: [{ latex: 'x_1', values: ['1', '2', '4', '5'] }, { latex: 'y_1', values: ['62', '68', '80', '86'] }] },
      { type: 'addExpression', latex: 'y_1\\sim mx_1+b' },
    ],
    approved: true,
  },
  {
    id: id(12),
    slug: 'custom_regression_model',
    title: 'Fit a quadratic or exponential model with ~',
    category: 'data_analysis',
    mode: 'hybrid',
    description: 'When the scatter is curved, replace the linear template with a model that matches the shape, using a tilde.',
    when_to_use: 'The data clearly bend, or the question says the model is quadratic or exponential.',
    when_not_to_use: 'A linear-looking cloud. Do not overfit four points with a high-degree polynomial unless the question asks for that form.',
    recognition_rule: 'Curved data + named model → custom regression with ~.',
    desmos_capability: 'Custom regressions such as y1 ~ a x1^2 + c, then reuse the stored parameters.',
    desmos_input_template: ['y1 ~ a x1^2 + b x1 + c'],
    student_steps: [
      'Enter the table.',
      'Type the model with ~ and the table column names.',
      'Read a, b, c (or the exponential parameters).',
      'Define f(x) with those parameters if you need a prediction such as f(0).',
    ],
    what_to_look_for: 'Parameter values and whether residuals look random.',
    why_it_works: 'The tilde tells Desmos to search for the parameter values that best match the column data.',
    common_mistakes: [
      'Writing y = instead of y1 ~.',
      'Using x instead of the table’s x1 name.',
    ],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'hard',
    desmos_only_possible: true,
    desmos_first_recommended: false,
    hybrid_recommended: true,
    estimated_time_savings: 'Replaces messy system-solving for parameters.',
    example_problem: 'Points (0, 5), (1, 8), (2, 17) appear quadratic. Fit y = ax^2 + c.',
    example_desmos_input: ['x1: 0,1,2', 'y1: 5,8,17', 'y1 ~ a x1^2 + c'],
    example_result: 'a = 3, c = 5, so y = 3x^2 + 5.',
    explanation: 'After the fit, a and c are stored. f(x) = a x^2 + c lets you test f(0) as the y-intercept of the model.',
    try_it_prompt: 'Fit y1 ~ a (b)^{x1} to (0, 2), (1, 6), (2, 18). What is a and b?',
    keywords: ['quadratic regression', 'exponential model', 'tilde', 'parameters', 'curve of best fit'],
    source_reference: ['Regressions – Desmos Help Center.pdf', 'Tables – Desmos Help Center.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Statistics and Data' },
      { test: 'SAT', topic: 'Quadratics' },
      { test: 'SAT', topic: 'Exponents and Radicals' },
      { test: 'ACT', topic: 'Statistics' },
      { test: 'ACT', topic: 'Quadratic Functions' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'addTable', columns: [{ latex: 'x_1', values: ['0', '1', '2'] }, { latex: 'y_1', values: ['5', '8', '17'] }] },
      { type: 'addExpression', latex: 'y_1\\sim a x_1^2+c' },
    ],
    approved: true,
  },
  {
    id: id(13),
    slug: 'regression_fit_quality',
    title: 'Read r, R², and residuals',
    category: 'statistics',
    mode: 'hybrid',
    description: 'After a regression, Desmos reports r for linear fits, R² for nonlinear fits, and residual distances.',
    when_to_use: 'The question asks how well a model fits, which model is better, or whether a linear model is reasonable.',
    when_not_to_use: 'If the question only wants a prediction from an already-given equation.',
    recognition_rule: '“How well does the model fit” → r / R² / residuals.',
    desmos_capability: 'Regression statistics, residual plot, Zoom Fit on residuals.',
    desmos_input_template: ['y1 ~ m x1 + b', 'inspect r and residuals'],
    student_steps: [
      'Run the regression.',
      'For a line, read r. Close to ±1 means a strong linear association.',
      'Plot residuals. A random scatter supports the model; a curve in the residuals means a different model may be better.',
    ],
    what_to_look_for: 'r or R², plus the shape of the residual plot — not just a pretty overlay on the data.',
    why_it_works: 'r measures linear association. Residuals are the leftover vertical errors. A pattern in leftovers means the model missed a trend.',
    common_mistakes: [
      'Treating a high r as proof of causation.',
      'Using r for a nonlinear model (Desmos reports R² there).',
    ],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'medium',
    desmos_only_possible: false,
    desmos_first_recommended: false,
    hybrid_recommended: true,
    estimated_time_savings: 'Gives fit stats that are painful to compute by hand.',
    example_problem: 'After fitting a line to a scatter, r = 0.97. What does that tell you?',
    example_desmos_input: ['y1 ~ m x1 + b'],
    example_result: 'The linear association is very strong and positive, but it still does not prove one variable causes the other.',
    explanation: 'You still have to say what r means in context. Desmos computes it; you interpret it.',
    try_it_prompt: 'Fit both a line and a quadratic to a bent scatter. Which residual plot looks more random?',
    keywords: ['correlation', 'r', 'R^2', 'residuals', 'goodness of fit', 'strength'],
    source_reference: ['Regressions – Desmos Help Center.pdf', 'Statistics – Desmos Help Center.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Statistics and Data' },
      { test: 'ACT', topic: 'Statistics' },
      { test: 'ACT', topic: 'Trend Analysis' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'addTable', columns: [{ latex: 'x_1', values: ['1', '2', '3', '4'] }, { latex: 'y_1', values: ['2', '4.1', '5.8', '8.2'] }] },
      { type: 'addExpression', latex: 'y_1\\sim mx_1+b' },
    ],
    approved: true,
  },
  {
    id: id(14),
    slug: 'stats_center_spread',
    title: 'Compute center and spread from a list',
    category: 'statistics',
    mode: 'desmos_first',
    description: 'Type the data as a list and use mean, median, min, max, stdev, or stats() to get summaries.',
    when_to_use: 'A list of numbers asks for mean, median, range, standard deviation, or a five-number summary.',
    when_not_to_use: 'A 3-number mean you can add in two seconds.',
    recognition_rule: 'A list of values + mean/median/spread → STATS FUNCTIONS.',
    desmos_capability: 'mean, median, min, max, stdev, stdevp, var, stats, count, total, quartile.',
    desmos_input_template: ['mean([1,5,5,10])', 'stats([1,5,5,10])'],
    student_steps: [
      'Store the numbers as a list, like L = [12, 15, 15, 18, 22].',
      'Type mean(L), median(L), or stats(L).',
      'Use stdev for a sample and stdevp only when the list is the whole population.',
    ],
    what_to_look_for: 'The requested summary number, and whether the question wants sample or population spread.',
    why_it_works: 'These functions implement the standard definitions. stats() also opens a five-number summary and boxplot.',
    common_mistakes: [
      'Using stdev when the problem treats the list as a full population (stdevp).',
      'Forgetting that median is safer than mean when an outlier is the trap.',
    ],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'easy',
    desmos_only_possible: true,
    desmos_first_recommended: true,
    hybrid_recommended: false,
    estimated_time_savings: 'Avoids long addition and sorted-list median work.',
    example_problem: 'For 1, 5, 5, 10, what is the mean and the median?',
    example_desmos_input: ['mean([1,5,5,10])', 'median([1,5,5,10])'],
    example_result: 'Mean 5.25, median 5.',
    explanation: 'Mean is the total divided by count. Median is the middle of the ordered list (average of the two center 5s).',
    try_it_prompt: 'Use stats([8, 9, 12, 12, 20]) and report the five-number summary.',
    keywords: ['mean', 'median', 'standard deviation', 'range', 'boxplot', 'five number', 'average'],
    source_reference: ['Statistics – Desmos Help Center.pdf', 'Supported Functions – Desmos Help Center.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Statistics and Data' },
      { test: 'ACT', topic: 'Statistics' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'addExpression', latex: 'L=[1,5,5,10]' },
      { type: 'addExpression', latex: 'mean(L)' },
      { type: 'addExpression', latex: 'median(L)' },
    ],
    approved: true,
  },
  {
    id: id(15),
    slug: 'data_visualizations',
    title: 'See shape with histogram, dotplot, or boxplot',
    category: 'statistics',
    mode: 'hybrid',
    description: 'Visualizations show shape, center, and spread, and they update if the list changes.',
    when_to_use: 'The question is about skew, outliers, or comparing two distributions.',
    when_not_to_use: 'When it only asks for a single computed mean.',
    recognition_rule: 'Shape / outlier / compare distributions → PLOT the list.',
    desmos_capability: 'histogram, dotplot, and boxplot from a list.',
    desmos_input_template: ['boxplot([1,5,5,10])'],
    student_steps: [
      'Enter the list.',
      'Type boxplot(L) or histogram(L).',
      'Read median, whiskers, and any far points. Use that to answer shape or outlier questions.',
    ],
    what_to_look_for: 'Center line, IQR box, whiskers, and isolated points.',
    why_it_works: 'A boxplot is a picture of the five-number summary. Extreme points stand out instead of hiding inside an average.',
    common_mistakes: ['Calling every far point an official outlier without checking the question’s definition.'],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'medium',
    desmos_only_possible: false,
    desmos_first_recommended: false,
    hybrid_recommended: true,
    estimated_time_savings: 'Makes skew and outliers visible immediately.',
    example_problem: 'The data 2, 3, 3, 4, 4, 4, 18 is described as “typical values near 4.” What feature should you check?',
    example_desmos_input: ['boxplot([2,3,3,4,4,4,18])'],
    example_result: 'The box sits near 3–4 and 18 is a high outlier that would pull the mean up.',
    explanation: 'Desmos draws the picture; you still have to say that 18 inflates the mean more than the median.',
    try_it_prompt: 'Compare boxplot([10,11,12,13,14]) with boxplot([10,11,12,13,40]).',
    keywords: ['boxplot', 'histogram', 'dotplot', 'skew', 'outlier', 'shape'],
    source_reference: ['Statistics – Desmos Help Center.pdf', 'Supported Functions – Desmos Help Center.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Statistics and Data' },
      { test: 'SAT', topic: 'Data Interpretation' },
      { test: 'ACT', topic: 'Statistics' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'addExpression', latex: 'boxplot([2,3,3,4,4,4,18])' },
    ],
    approved: true,
  },
  {
    id: id(16),
    slug: 'slider_parameter_match',
    title: 'Use a slider to match a parameter',
    category: 'functions',
    mode: 'desmos_first',
    description: 'An undefined letter becomes a slider. Drag it until the graph matches a condition.',
    when_to_use: 'A family of functions y = a x + b or y = a(x-h)^2 + k, and you must find the parameter that fits a point, intercept, or shape.',
    when_not_to_use: 'If a is already isolated algebraically in one step.',
    recognition_rule: 'Unknown coefficient + “which value of a” → SLIDER.',
    desmos_capability: 'Sliders, and movable points such as (a, f(a)) that trace a curve.',
    desmos_input_template: ['y = a x^2 + 3', 'a slider'],
    student_steps: [
      'Type the family with the unknown letter left free.',
      'Accept the slider Desmos creates.',
      'Drag until the graph hits the required point or matches the given graph.',
    ],
    what_to_look_for: 'The slider value that makes the condition true.',
    why_it_works: 'Each slider value is one member of the family. The value that satisfies the geometric condition is the parameter the question wants.',
    common_mistakes: ['Changing two sliders at once and losing track of which one matters.'],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'medium',
    desmos_only_possible: true,
    desmos_first_recommended: true,
    hybrid_recommended: false,
    estimated_time_savings: 'Replaces guess-and-check algebra on parameter questions.',
    example_problem: 'For f(x) = a x + 2, what a makes the line pass through (3, 11)?',
    example_desmos_input: ['y=ax+2', '(3,11)'],
    example_result: 'a = 3.',
    explanation: 'The point is on the line when 11 = 3a + 2. The slider that threads (3, 11) is a = 3.',
    try_it_prompt: 'Graph y = a(x-2)^2 + 1 and find a so the graph also contains (4, 9).',
    keywords: ['slider', 'parameter', 'value of a', 'family of functions', 'trace'],
    source_reference: ['Functions – Desmos Help Center.pdf', 'Getting Started_ Desmos Graphing Calculator.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Functions' },
      { test: 'SAT', topic: 'Linear Functions' },
      { test: 'SAT', topic: 'Quadratics' },
      { test: 'ACT', topic: 'Function Notation' },
      { test: 'ACT', topic: 'Quadratic Functions' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'createSlider', variable: 'a', value: 1, min: -6, max: 6, step: 0.1 },
      { type: 'addExpression', latex: 'y=ax+2' },
      { type: 'addPoint', x: 3, y: 11, label: 'target' },
    ],
    approved: true,
  },
  {
    id: id(17),
    slug: 'circle_center_radius',
    title: 'Graph a circle to read center and radius',
    category: 'geometry',
    mode: 'desmos_first',
    description: 'x^2 + y^2 = r^2, or (x-h)^2 + (y-k)^2 = r^2, graphs as a circle you can measure from the labeled points.',
    when_to_use: 'The equation of a circle is given and the question asks for center, radius, or a point on the circle.',
    when_not_to_use: 'A pure geometry diagram with no coordinates.',
    recognition_rule: 'x² + y² (or shifted) → CIRCLE; center is (h, k), radius is r.',
    desmos_capability: 'Implicit circle graphs and inequality disks such as x^2 + y^2 < 4.',
    desmos_input_template: ['(x-h)^2+(y-k)^2=r^2'],
    student_steps: [
      'Type the circle equation.',
      'Read the center as the middle of the graph.',
      'Hover a point on the circle, or compare to the r^2 in the equation, to get the radius.',
    ],
    what_to_look_for: 'Center coordinates and the distance from center to the curve.',
    why_it_works: 'The equation is the set of points at a fixed distance r from (h, k). The graph is that definition.',
    common_mistakes: [
      'Using r^2 as the radius.',
      'Flipping the signs of h and k.',
    ],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'medium',
    desmos_only_possible: true,
    desmos_first_recommended: true,
    hybrid_recommended: false,
    estimated_time_savings: 'Helps when the equation is expanded and completing the square is messy.',
    example_problem: 'What is the radius of x^2 + y^2 = 25?',
    example_desmos_input: ['x^2+y^2=25'],
    example_result: 'Center (0, 0), radius 5.',
    explanation: '25 is r^2, so r = 5. The graph meets the axes at ±5.',
    try_it_prompt: 'Graph (x-2)^2 + (y+1)^2 = 9. Name the center and a point on the circle.',
    keywords: ['circle', 'radius', 'center', 'x^2 + y^2', 'disk'],
    source_reference: ['Inequalities and Restrictions – Desmos Help Center.pdf', 'Getting Started_ Desmos Graphing Calculator.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Circles' },
      { test: 'SAT', topic: 'Coordinate Geometry' },
      { test: 'ACT', topic: 'Plane Geometry' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'addExpression', latex: 'x^2+y^2=25' },
      { type: 'setViewport', bounds: { left: -8, right: 8, bottom: -8, top: 8 } },
    ],
    approved: true,
  },
  {
    id: id(18),
    slug: 'coordinate_distance_midpoint',
    title: 'Use distance and midpoint functions',
    category: 'geometry',
    mode: 'hybrid',
    description: 'Desmos can compute distance((x1,y1),(x2,y2)) and midpoint of two points. Still know what the number means.',
    when_to_use: 'Coordinate geometry with messy numbers, or when you want a check after using the formulas.',
    when_not_to_use: 'Clean lattice points like (0,0) and (3,4) — the 3-4-5 triangle is faster mentally.',
    recognition_rule: 'Two points + distance/midpoint → function, but prefer mental 3-4-5 when obvious.',
    desmos_capability: 'distance and midpoint functions; plotting the two points.',
    desmos_input_template: ['distance((0,2),(4,5))', 'midpoint((0,2),(4,5))'],
    student_steps: [
      'Plot both points.',
      'Type distance(...) or midpoint(...).',
      'If the question is a word problem, say what that length or midpoint represents.',
    ],
    what_to_look_for: 'The computed length or the midpoint coordinate.',
    why_it_works: 'Distance is the Pythagorean theorem. Midpoint averages each coordinate. Desmos evaluates those definitions.',
    common_mistakes: ['Reporting distance when the question asked for midpoint, or leaving the answer as a point when it wanted a length.'],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'easy',
    desmos_only_possible: true,
    desmos_first_recommended: false,
    hybrid_recommended: true,
    estimated_time_savings: 'Worth it only when the coordinates are ugly.',
    example_problem: 'What is the distance from (0, 2) to (4, 5)?',
    example_desmos_input: ['distance((0,2),(4,5))'],
    example_result: '5.',
    explanation: 'The legs are 4 and 3, so the hypotenuse is 5. Desmos is running that same theorem.',
    try_it_prompt: 'Find the midpoint of (–3, 8) and (5, –2).',
    keywords: ['distance', 'midpoint', 'coordinate', 'length', 'segment'],
    source_reference: ['Supported Functions – Desmos Help Center.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Coordinate Geometry' },
      { test: 'SAT', topic: 'Triangles' },
      { test: 'ACT', topic: 'Plane Geometry' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'addPoint', x: 0, y: 2, label: 'A' },
      { type: 'addPoint', x: 4, y: 5, label: 'B' },
      { type: 'addExpression', latex: 'distance((0,2),(4,5))' },
    ],
    approved: true,
  },
  {
    id: id(19),
    slug: 'trig_evaluate_degree_mode',
    title: 'Evaluate trig in degree mode',
    category: 'geometry',
    mode: 'desmos_first',
    description: 'SAT/ACT angle measures are almost always in degrees. Switch Desmos to degrees, then use sin, cos, tan.',
    when_to_use: 'A right-triangle or function question needs a sine, cosine, or tangent value, or a graph of a trig function.',
    when_not_to_use: 'Exact special angles you already know (30-60-90, 45-45-90) if the answer is an exact radical.',
    recognition_rule: 'sin/cos/tan of a degree measure → DEGREE MODE, then evaluate.',
    desmos_capability: 'Trig and inverse trig functions; degree mode.',
    desmos_input_template: ['sin(40)', 'tan(x)'],
    student_steps: [
      'Turn degree mode on.',
      'Type sin(θ), cos(θ), or tan(θ).',
      'If you are solving an equation, graph y = sin(x) and y = the other side and read intersections.',
    ],
    what_to_look_for: 'The numeric value, or intersection x-values on a trig graph.',
    why_it_works: 'These functions return the matching right-triangle ratio (or unit-circle value). Degree mode makes 40 mean 40°, not 40 radians.',
    common_mistakes: [
      'Leaving the calculator in radians.',
      'Using tan when the triangle sides call for sine.',
    ],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'medium',
    desmos_only_possible: true,
    desmos_first_recommended: true,
    hybrid_recommended: false,
    estimated_time_savings: 'Needed for non-special angles.',
    example_problem: 'In a right triangle, opposite = 5 and hypotenuse = 13. What is the larger acute angle to the nearest degree?',
    example_desmos_input: ['arcsin(5/13)'],
    example_result: 'About 23°, so the other acute angle is about 67°.',
    explanation: 'sin θ = opposite/hypotenuse. Inverse sine returns θ. The complementary angle is 90 minus that.',
    try_it_prompt: 'Graph y = sin(x) in degree mode from 0 to 360. Where is the first peak?',
    keywords: ['sine', 'cosine', 'tangent', 'trig', 'degrees', 'arcsin'],
    source_reference: ['Supported Functions – Desmos Help Center.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Trigonometry' },
      { test: 'ACT', topic: 'Trigonometry' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'setDegreeMode', degrees: true },
      { type: 'addExpression', latex: 'y=\\sin(x)' },
      { type: 'setViewport', bounds: { left: -20, right: 380, bottom: -2, top: 2 } },
    ],
    approved: true,
  },
  {
    id: id(20),
    slug: 'exponential_vs_linear',
    title: 'Compare linear and exponential growth on one graph',
    category: 'advanced_math',
    mode: 'desmos_first',
    description: 'Graph both models. The intersection and the later heights show which grows faster and when they meet.',
    when_to_use: 'Two formulas, one linear and one exponential, and the question asks when they are equal or which is larger later.',
    when_not_to_use: 'A one-step percent-of question with no comparison.',
    recognition_rule: 'Linear vs exponential + “when equal / which larger” → GRAPH BOTH.',
    desmos_capability: 'Plot both functions and read the intersection plus later points.',
    desmos_input_template: ['y = mx + b', 'y = a(b)^x'],
    student_steps: [
      'Graph both models.',
      'Read the intersection if the question asks when they match.',
      'Compare heights to the right of that point to see which grows faster.',
    ],
    what_to_look_for: 'The crossing and the long-run gap.',
    why_it_works: 'Equal outputs are intersections. Exponential growth outruns a constant slope once the multiplier has time to compound.',
    common_mistakes: ['Comparing y-intercepts and assuming that ranking never changes.'],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'medium',
    desmos_only_possible: true,
    desmos_first_recommended: true,
    hybrid_recommended: false,
    estimated_time_savings: 'Avoids solving a = b^x by hand.',
    example_problem: 'Plan A is y = 20x + 40. Plan B is y = 40(1.2)^x. After how many whole years is B first larger?',
    example_desmos_input: ['y=20x+40', 'y=40(1.2)^x'],
    example_result: 'They meet near x = 6. After that, the exponential is higher.',
    explanation: 'The intersection is when the plans cost the same. To the right, 1.2^x grows faster than +20 per year.',
    try_it_prompt: 'Compare y = 3x and y = 2^x. Which is larger at x = 1 and at x = 5?',
    keywords: ['exponential', 'linear', 'growth', 'compare', 'when equal'],
    source_reference: ['Getting Started_ Desmos Graphing Calculator.pdf', 'Functions – Desmos Help Center.pdf', 'Supported Functions – Desmos Help Center.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Exponents and Radicals' },
      { test: 'SAT', topic: 'Functions' },
      { test: 'SAT', topic: 'Nonlinear Equations' },
      { test: 'SAT', topic: 'Linear Functions' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'plotExpressions', latex: ['y=20x+40', 'y=40(1.2)^x'] },
      { type: 'setViewport', bounds: { left: -1, right: 12, bottom: -10, top: 280 } },
    ],
    approved: true,
  },
  {
    id: id(21),
    slug: 'polynomial_roots_extrema',
    title: 'Read polynomial roots and turning points',
    category: 'advanced_math',
    mode: 'desmos_first',
    description: 'A polynomial graph shows every real root as an x-intercept and every local max/min as a turning point.',
    when_to_use: 'Cubic or higher polynomials, “how many real solutions,” or local max/min questions.',
    when_not_to_use: 'Factoring a simple quadratic you can see instantly.',
    recognition_rule: 'Polynomial + roots or local max/min → GRAPH and count intercepts / turns.',
    desmos_capability: 'Points of interest for intercepts and extrema.',
    desmos_input_template: ['y = polynomial'],
    student_steps: [
      'Graph the polynomial.',
      'Count x-intercepts for real roots.',
      'Read turning-point y-values for local max/min.',
    ],
    what_to_look_for: 'How many times it crosses the x-axis, and the gray extrema.',
    why_it_works: 'Real roots are x-intercepts. Local extrema are where the graph turns around.',
    common_mistakes: ['Missing a root that only touches the axis.', 'Zooming so far out that a tiny wiggle disappears.'],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'medium',
    desmos_only_possible: true,
    desmos_first_recommended: true,
    hybrid_recommended: false,
    estimated_time_savings: 'Beats synthetic division on “how many real zeros” questions.',
    example_problem: 'How many real solutions does x^3 - 3x + 1 = 0 have?',
    example_desmos_input: ['y=x^3-3x+1'],
    example_result: 'Three x-intercepts, so three real solutions.',
    explanation: 'The cubic wiggles across the x-axis three times. Each crossing is one real root.',
    try_it_prompt: 'Graph y = x^3 - x and name the local max and min.',
    keywords: ['polynomial', 'cubic', 'real solutions', 'turning point', 'local maximum'],
    source_reference: ['Getting Started_ Desmos Graphing Calculator.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Polynomials' },
      { test: 'SAT', topic: 'Nonlinear Equations' },
      { test: 'ACT', topic: 'Quadratic Functions' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'addExpression', latex: 'y=x^3-3x+1' },
      { type: 'setViewport', bounds: { left: -4, right: 4, bottom: -6, top: 6 } },
    ],
    approved: true,
  },
  {
    id: id(22),
    slug: 'word_problem_intersection_interpret',
    title: 'Find the number, then interpret it',
    category: 'algebra',
    mode: 'hybrid',
    description: 'Desmos can find the intersection, but a context question still needs you to say what that number means.',
    when_to_use: 'Two real-world models (cost, distance, population) and the question asks when they match or what that time/amount represents.',
    when_not_to_use: 'A pure “solve the system” question with no story.',
    recognition_rule: 'Story + two models + “what does it mean” → INTERSECTION, then INTERPRET.',
    desmos_capability: 'Graph both models and read the intersection, then map coordinates back to units.',
    desmos_input_template: ['y = model A', 'y = model B'],
    student_steps: [
      'Graph both real-world formulas.',
      'Read the intersection.',
      'x is usually time or quantity. y is usually the shared amount. Answer in those units.',
    ],
    what_to_look_for: 'The coordinate, then the sentence that names the units.',
    why_it_works: 'The math solution is the crossing. The SAT/ACT score comes from translating that crossing into the story.',
    common_mistakes: [
      'Stopping at (2, 9) when the question asked “after how many weeks.”',
      'Using the wrong coordinate for the requested quantity.',
    ],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'medium',
    desmos_only_possible: false,
    desmos_first_recommended: false,
    hybrid_recommended: true,
    estimated_time_savings: 'Desmos gets the number; you still write the meaning.',
    example_problem: 'A gym charges 20 + 15m dollars. A pass costs 80 + 5m. After how many months is the total the same?',
    example_desmos_input: ['y=20+15x', 'y=80+5x'],
    example_result: 'They meet at (6, 110): after 6 months both cost $110.',
    explanation: 'x = 6 is months until the plans match. 110 is the matching dollar amount — only report 6 if the question asked for months.',
    try_it_prompt: 'Car A: d = 40t. Car B: d = 25t + 60. When is A caught up, and what does the y-value mean?',
    keywords: ['word problem', 'represents', 'in context', 'after how many', 'models'],
    source_reference: ['Getting Started_ Desmos Graphing Calculator.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Linear Equations' },
      { test: 'SAT', topic: 'Systems of Equations' },
      { test: 'SAT', topic: 'Linear Functions' },
      { test: 'ACT', topic: 'Linear Equations' },
      { test: 'ACT', topic: 'Systems of Equations' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'plotExpressions', latex: ['y=20+15x', 'y=80+5x'] },
      { type: 'setViewport', bounds: { left: -1, right: 12, bottom: -10, top: 160 } },
      { type: 'addPoint', x: 6, y: 110, label: 'same cost' },
    ],
    approved: true,
  },
  {
    id: id(23),
    slug: 'plot_points_and_zoom',
    title: 'Plot points, pan, and set the window',
    category: 'algebra',
    mode: 'hybrid',
    description: 'Type (x, y) to plot a point. Pan, zoom, or set axis bounds so the useful part of the graph is actually visible.',
    when_to_use: 'Given coordinates, a graph that is off-screen, or a window that hides an intersection.',
    when_not_to_use: 'A single labeled point already on a provided figure.',
    recognition_rule: 'Nothing useful on screen → change the VIEWPORT before deciding the graph “has no solution.”',
    desmos_capability: 'Point plotting, pan/zoom, and Graph Settings window bounds.',
    desmos_input_template: ['(1, 3)', 'set viewport to the data range'],
    student_steps: [
      'Plot given points as (x, y).',
      'If the intersection is missing, zoom out or set bounds that include the expected region.',
      'Use Default Viewport only after you have finished reading values.',
    ],
    what_to_look_for: 'The points themselves, and whether the crossing is simply off-screen.',
    why_it_works: 'A graph is infinite. A small window can hide the solution you already entered correctly.',
    common_mistakes: ['Concluding two lines never meet because you are zoomed in on the origin.'],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'easy',
    desmos_only_possible: false,
    desmos_first_recommended: false,
    hybrid_recommended: true,
    estimated_time_savings: 'Prevents false “no solution” errors.',
    example_problem: 'Graph y = 0.2x + 40 and y = 80. Where do they meet?',
    example_desmos_input: ['y=0.2x+40', 'y=80'],
    example_result: 'They meet at x = 200, which is invisible on the default –10 to 10 window.',
    explanation: 'Widen the x-axis. The math was fine; the window was too small.',
    try_it_prompt: 'Plot (12, 35) and (18, 50). Adjust the window until both points are easy to see.',
    keywords: ['plot', 'point', 'zoom', 'window', 'viewport', 'coordinates'],
    source_reference: ['Getting Started_ Desmos Graphing Calculator.pdf', 'Tables – Desmos Help Center.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Coordinate Geometry' },
      { test: 'SAT', topic: 'Linear Functions' },
      { test: 'SAT', topic: 'Data Interpretation' },
      { test: 'ACT', topic: 'Reading Graphs and Tables' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'plotExpressions', latex: ['y=0.2x+40', 'y=80'] },
      { type: 'setViewport', bounds: { left: -10, right: 240, bottom: 20, top: 100 } },
    ],
    approved: true,
  },
  {
    id: id(24),
    slug: 'combinations_permutations',
    title: 'Count arrangements with nCr and nPr',
    category: 'statistics',
    mode: 'hybrid',
    description: 'nCr counts unordered groups. nPr counts ordered arrangements. Desmos evaluates both.',
    when_to_use: 'A counting question with “choose,” “committees,” or “arrangements” and ugly factorials.',
    when_not_to_use: 'Tiny cases like 4C2 that you can list.',
    recognition_rule: 'Order matters → nPr. Order does not → nCr.',
    desmos_capability: 'nCr and nPr from the number-theory function set.',
    desmos_input_template: ['nCr(6, 2)', 'nPr(6, 2)'],
    student_steps: [
      'Decide whether order matters.',
      'Type nCr(n, r) or nPr(n, r).',
      'If the story has extra conditions (already includes one person), adjust n or r first.',
    ],
    what_to_look_for: 'The integer count, after you chose the correct function.',
    why_it_works: 'These are the standard counting formulas. Desmos computes them; you still classify the story.',
    common_mistakes: ['Using nPr when the committee is unordered.', 'Using nCr for a password or lineup.'],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'medium',
    desmos_only_possible: true,
    desmos_first_recommended: false,
    hybrid_recommended: true,
    estimated_time_savings: 'Saves factorial arithmetic after the classification is correct.',
    example_problem: 'How many 2-person committees can be formed from 6 students?',
    example_desmos_input: ['nCr(6,2)'],
    example_result: '15.',
    explanation: 'A committee is unordered, so combinations, not permutations. nPr(6,2) = 30 would double-count each pair.',
    try_it_prompt: 'How many ways can 6 runners finish first and second? Which function is that?',
    keywords: ['combination', 'permutation', 'nCr', 'nPr', 'choose', 'arrangements'],
    source_reference: ['Supported Functions – Desmos Help Center.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Probability' },
      { test: 'ACT', topic: 'Probability' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'addExpression', latex: 'nCr(6,2)' },
      { type: 'addExpression', latex: 'nPr(6,2)' },
    ],
    approved: true,
  },
  {
    id: id(25),
    slug: 'list_min_max_sort',
    title: 'Sort a list and read min or max',
    category: 'data_analysis',
    mode: 'desmos_first',
    description: 'Lists can be sorted or scanned for min and max without rewriting the data by hand.',
    when_to_use: 'A messy list needs the largest value, smallest value, or an ordered version.',
    when_not_to_use: 'Three tidy numbers.',
    recognition_rule: 'Long list + least/greatest → min / max / sort.',
    desmos_capability: 'min, max, sort, unique, join, count, total.',
    desmos_input_template: ['sort([5,1,5,10])', 'max(L)'],
    student_steps: [
      'Store the list.',
      'Use min(L), max(L), or sort(L).',
      'unique(L) if the question wants distinct values only.',
    ],
    what_to_look_for: 'The extreme value or the ordered list.',
    why_it_works: 'These list operations apply the ordinary definitions to every entry at once.',
    common_mistakes: ['Using max when the question asked for the second-largest after duplicates are removed.'],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'easy',
    desmos_only_possible: true,
    desmos_first_recommended: true,
    hybrid_recommended: false,
    estimated_time_savings: 'Useful on long SAT/ACT data lists.',
    example_problem: 'What is the largest value in 5, 1, 5, 10, 8?',
    example_desmos_input: ['max([5,1,5,10,8])'],
    example_result: '10.',
    explanation: 'max scans the list. sort would put 10 at the end, which is the same information.',
    try_it_prompt: 'Use unique([3,3,4,4,4,9]) and then max of that result.',
    keywords: ['min', 'max', 'sort', 'list', 'greatest', 'least'],
    source_reference: ['Supported Functions – Desmos Help Center.pdf', 'Tables – Desmos Help Center.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Statistics and Data' },
      { test: 'SAT', topic: 'Data Interpretation' },
      { test: 'ACT', topic: 'Statistics' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'addExpression', latex: 'L=[5,1,5,10,8]' },
      { type: 'addExpression', latex: 'max(L)' },
    ],
    approved: true,
  },
  {
    id: id(26),
    slug: 'simple_arithmetic_skip_desmos',
    title: 'Skip Desmos on one-step mental math',
    category: 'manual',
    mode: 'manual_first',
    description: 'If the fastest valid method is five seconds of arithmetic or a definition, do not open the calculator.',
    when_to_use: 'Always use this rule: Desmos is a speed tool, not a default.',
    when_not_to_use: 'Never apply this skip to a messy system, quadratic, regression, or inequality region.',
    recognition_rule: 'If you can finish it faster than typing, do not graph it.',
    desmos_capability: 'None required.',
    desmos_input_template: [],
    student_steps: [
      'Ask: can I do this in under 10 seconds without a calculator?',
      'If yes, compute it and move on.',
      'If no, pick a Desmos-first or hybrid strategy.',
    ],
    what_to_look_for: 'Nothing on a graph — this is a time-management rule.',
    why_it_works: 'Opening Desmos, typing, and reading a graph can cost more time than the algebra on a one-step item.',
    common_mistakes: ['Graphing 3x + 7 = 22 and waiting for an intersection you could have done mentally.'],
    sat_applicable: true,
    act_applicable: true,
    difficulty: 'easy',
    desmos_only_possible: false,
    desmos_first_recommended: false,
    hybrid_recommended: false,
    estimated_time_savings: 'Saves 15–20s of calculator overhead.',
    example_problem: 'If 3x + 7 = 22, what is x?',
    example_desmos_input: [],
    example_result: 'x = 5. Done mentally: subtract 7, divide by 3.',
    explanation: 'A graph of y = 3x+7 and y = 22 works, but it is slower and teaches the wrong habit for easy items.',
    try_it_prompt: 'Decide: is “what is 15% of 80” a Desmos problem? Why or why not?',
    keywords: ['mental math', 'one step', 'simple', 'arithmetic', 'definition'],
    source_reference: ['Getting Started_ Desmos Graphing Calculator.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Linear Equations' },
      { test: 'SAT', topic: 'Percentages' },
      { test: 'SAT', topic: 'Ratios and Proportions' },
      { test: 'ACT', topic: 'Linear Equations' },
      { test: 'ACT', topic: 'Rational Numbers' },
    ],
    agent_actions: [],
    approved: true,
  },
  {
    id: id(27),
    slug: 'inference_tests_review',
    title: 'Inference tests and probability distributions',
    category: 'statistics',
    mode: 'hybrid',
    description: 'Desmos can run z-tests, t-tests, chi-square tests, and graph common distributions. SAT/ACT items almost never need the full inference menu.',
    when_to_use: 'A rare ACT science-style or advanced stats item that names a normal curve, binomial count, or p-value.',
    when_not_to_use: 'Standard SAT Math. Do not introduce z-tests on a mean/median question.',
    recognition_rule: 'Named distribution or hypothesis test → Inference menu. Otherwise skip.',
    desmos_capability: 'normaldist, binomialdist, ztest, ttest, chisqtest, random().',
    desmos_input_template: ['normaldist(0,1)', 'binomialdist(10,0.3)'],
    student_steps: [
      'Confirm the test actually asked for a distribution or inference result.',
      'Enter the matching distribution or test.',
      'Read the requested probability, not every extra statistic.',
    ],
    what_to_look_for: 'The probability or test output the question named.',
    why_it_works: 'These tools implement the named distributions. They are easy to misuse on SAT/ACT if the question did not ask for them.',
    common_mistakes: ['Running a z-test when the question only wanted a mean.'],
    sat_applicable: false,
    act_applicable: true,
    difficulty: 'hard',
    desmos_only_possible: false,
    desmos_first_recommended: false,
    hybrid_recommended: true,
    estimated_time_savings: 'Only useful on the rare item that names the tool.',
    example_problem: 'A fair coin is flipped 10 times. What is the probability of exactly 3 heads?',
    example_desmos_input: ['binomialdist(10,0.5)'],
    example_result: 'This is a binomial model. Most SAT questions expect nCr instead of the inference menu.',
    explanation: 'Keep this strategy off automatic tutoring until a human reviews SAT/ACT fit.',
    try_it_prompt: 'Graph normaldist(100, 15) and describe what the middle peak represents.',
    keywords: ['normal', 'binomial', 'z-test', 'p-value', 'distribution', 'inference'],
    source_reference: ['Statistics – Desmos Help Center.pdf', 'Supported Functions – Desmos Help Center.pdf'],
    topic_keys: [
      { test: 'SAT', topic: 'Probability' },
      { test: 'ACT', topic: 'Probability' },
      { test: 'ACT', topic: 'Statistics' },
    ],
    agent_actions: [
      { type: 'clearAgentWork' },
      { type: 'addExpression', latex: 'binomialdist(10,0.5)' },
    ],
    approved: false,
  },
]

export const APPROVED_STRATEGIES = DESMOS_STRATEGIES.filter((s) => s.approved)

export function getStrategyBySlug(slug: string): DesmosStrategy | undefined {
  return DESMOS_STRATEGIES.find((s) => s.slug === slug)
}

export function getStrategyById(idValue: string): DesmosStrategy | undefined {
  return DESMOS_STRATEGIES.find((s) => s.id === idValue)
}

export function strategiesByCategory(category: DesmosStrategy['category']): DesmosStrategy[] {
  return APPROVED_STRATEGIES.filter((s) => s.category === category)
}
